### ISSUE TITLE
ProcessLookupError: No such process after check-in

### ISSUE THREAD

**Issue by helpdeskdan** [jdholtz/auto-southwest-check-in#110]
### Description

Not sure if this is a problem.  It appears to work great, despite the exception: 

<pre>
Exception ignored in: <function Chrome.__del__ at 0x7f549d04a430>
Traceback (most recent call last):
  File "/home/dan/southwest/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 769, in __del__
    self.quit()
  File "/home/dan/southwest/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 68, in quit
    super().quit()
  File "/home/dan/southwest/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 723, in quit
    self.service.process.kill()
  File "/usr/lib/python3.8/subprocess.py", line 1943, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.8/subprocess.py", line 1933, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Error terminating service process.
Traceback (most recent call last):
  File "/home/dan/southwest/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 165, in _terminate_process
    self.process.terminate()
  File "/usr/lib/python3.8/subprocess.py", line 1938, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python3.8/subprocess.py", line 1933, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
Checking in to flight from 'Des Moines' to 'Salt Lake City' for Daniel Schmidt

Successfully checked in to flight from '...
</pre>

### To Reproduce

Note: I don't use chrome, I use chromium-chromedriver.  

### Expected Behavior

No exception?  Despite not finding any process to kill, it continues and appears to work just fine.  Maybe some defuncts....  say, shouldn't it exit when done? 

<pre>
$ ps ax | grep chrome
  83517 pts/3    Z+     0:01 [chrome] <defunct>
  83518 pts/3    Z+     0:00 [chromedriver] <defunct>
</pre>

### Version

Auto-Southwest Check-In v4.1

### Additional context

Pretty standard
<pre>
{
    "chromedriver_path": "/usr/bin/chromedriver",
    "chrome_version": 114,
    "check_fares": false,
</pre>

P.S.  Thanks for the project!

**Comment by jdholtz** [comment]
Thanks for filing this issue! Chrome should exit when the script exits (and probably even earlier, when driver.quit() is called). Could you attach the logs of when the exception was thrown so I can debug this better?

Does this exception happen every time you run the script or is this the only time it was thrown (a.k.a is it repeatable)?

**Comment by helpdeskdan** [comment]
There's little of interest in the logs.  The error would have been thrown on this day, and this is the entirety of the logs from that day.  I hit ctrl-c about 10 minutes later, no log entry for that. 

<pre>
 75 2023-06-26 11:29:55 DEBUG Process-1:1[checkin_scheduler]: Refreshing headers for current session
 76 2023-06-26 11:29:55 DEBUG Process-1:1[webdriver]: Starting webdriver for current session
 77 2023-06-26 11:29:58 DEBUG Process-1:1[webdriver]: Loading Southwest Check-In page
 78 2023-06-26 11:30:07 DEBUG Process-1:1[webdriver]: Filling out a check-in form to get valid headers
 79 2023-06-26 11:30:09 DEBUG Process-1:1[webdriver]: Setting valid headers from previous request
 80 2023-06-26 11:30:09 DEBUG Process-1:1[checkin_handler]: Sleeping until check-in: 585 seconds...
 81 2023-06-26 11:39:55 DEBUG Process-1:1[checkin_handler]: Attempting to check in
 82 2023-06-26 11:39:55 DEBUG Process-1:1[checkin_handler]: Making GET request to check in
 83 2023-06-26 11:40:05 DEBUG Process-1:1[utils]: Successfully made request after 2 attempts
 84 2023-06-26 11:40:05 DEBUG Process-1:1[checkin_handler]: Making POST request to check in
 85 2023-06-26 11:40:09 DEBUG Process-1:1[utils]: Successfully made request after 1 attempts
 86 2023-06-26 11:40:09 DEBUG Process-1:1[checkin_handler]: Successfully checked in!
 87 2023-06-26 11:40:09 DEBUG Process-1:1[notification_handler]: Sending successful check-in notification...
</pre>

(sigh)  No, it does not appear to be repeatable.  I ran the code again and it checked me in the flight I was already checked in.  Didn't throw any errors.  Sorry, that's not terribly helpful.

**Comment by jdholtz** [comment]
There are random issues that people get from the webdriver every so often and this is probably one of them. The good thing is that this exception didn’t actually affect the check-in process at all. 

Due to that and the fact that it doesn’t seem to come directly from the script, I’ll close this for now. Feel free to reopen this or make a new issue if you run into this issue (or a similar one) in the future.

**Comment by jdholtz** [comment]
@helpdeskdan, in the [fix-process-handling](https://github.com/jdholtz/auto-southwest-check-in/tree/fix-process-handling) branch I added functionality so Chrome zombie processes should no longer appear. I know this wasn't the exact issue that you had, but it was part of the concern so I just wanted to let you know that the zombie processes have been fixed

**Comment by helpdeskdan** [comment]
Thanks!
