### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by Turkey-Buzzard** [jdholtz/auto-southwest-check-in#115]
### Description

Python script worked but I got an ignored exception. Do I have something missing in my environment? Thanks.

<snip>

Successfully logged in to David Lastname's account

Successfully scheduled the following flights to check in for David Lastname:
Flight from San Jose to Lihue (Kauai) at 2023-07-06 15:25:00 UTC
Flight from Lihue (Kauai) to San Jose at 2023-07-17 00:05:00 UTC

Checking in to flight from 'San Jose' to 'Lihue (Kauai)' for David Lastname

Successfully checked in to flight from 'San Jose' to 'Lihue (Kauai)' for David Lastname!
David Lastname B53!
Carolyn Lastname got B54!

Exception ignored in: <function Chrome.__del__ at 0x0000015A9E54FE20>
Traceback (most recent call last):
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
    self.quit()
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 68, in quit
    super().quit()
  File "C:\Users\David\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid

### To Reproduce

python southwest.py USERNAME PASSWORD

### Version

Auto-Southwest Check-In v4.1

**Comment by jdholtz** [comment]
This is an issue with `undetected_chromedriver` but it won’t affect the execution of this script, so it can be safely ignored. There are a few proposed fixes in undetected_chromedriver, but I’ll catch the exception in this script because other people have run into this as well (and I’m not sure if the fix will ever be added to undetected_chromedriver).

**Comment by Turkey-Buzzard** [comment]
Thanks for the response. Terrific script.

**Comment by jdholtz** [comment]
I looked at the error a bit more and it appears to happen at the end of the script where I don't have direct control in catching the error. Since this exception can be safely ignored, I will just wait for it to be fixed in the `undetected_chromedriver` repository.
