### ISSUE TITLE
EOFError: Ran out of input in v4.2

### ISSUE THREAD

**Issue by rbrotz69** [jdholtz/auto-southwest-check-in#118]
### Description

I am not getting the following error since I upgraded from v4.1 to v4.2.  Any help would be appreciated.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MediaLaptop\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MediaLaptop\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input

### To Reproduce

To upgraded I ran
git pull
pip install -r requirements.txt
southwest.py

config.json [I have valid info in the confirmation.]
{
"notification_level": 1,
"retrieval_interval": 0,
"chrome_version": 114,
"reservations": [
{"confirmationNumber": "XXXXXX", "firstName": "RealFName", "lastName": "RealLname"}
}

### Version

Auto-Southwest Check-In v4.2

### Additional context

I'm using Chrome v114

**Comment by jdholtz** [comment]
Thanks for reporting this. Does this issue happen every single time? Also, can you paste in the full traceback (if what you pasted isn’t the full traceback) and attach your logs?

**Comment by jdholtz** [comment]
Thanks. For some reason the log file shows up as an XML (plist) for me. However, I think this issue is the same as #119. So far, I've only tried this in Linux and I think there is an issue when running it on Windows and macOS. I will fix this within the next few days but for now you can use the Docker image for v4.2 or revert back to v4.1 to continue to use this script.

**Comment by jdholtz** [comment]
Hey @rbrotz69. I made a potential fix for this in the [fix-process-handling](https://github.com/jdholtz/auto-southwest-check-in/tree/fix-process-handling) branch after being able to reproduce the issue. Would you be able to test out the changes on this new branch?

You can do so by issuing the following commands:
```
git pull
git checkout fix-process-handling
python southwest.py ...
```

**Comment by rbrotz69** [comment]
Hi Joey,

I ran the commands and now I'm getting a slightly different error message:

C:\Users\MediaLaptop\Documents\auto-southwest-check-in>git pull
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 12 (delta 9), reused 12 (delta 9), pack-reused 0
Unpacking objects: 100% (12/12), 4.23 KiB | 3.00 KiB/s, done.
From https://github.com/jdholtz/auto-southwest-check-in
 * [new branch]      fix-process-handling -> origin/fix-process-handling
Already up to date.

C:\Users\MediaLaptop\Documents\auto-southwest-check-in>git checkout
fix-process-handling
Switched to a new branch 'fix-process-handling'
branch 'fix-process-handling' set up to track 'origin/fix-process-handling'.

C:\Users\MediaLaptop\Documents\auto-southwest-check-in>southwest.py
C:\Users\MediaLaptop\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py:678:
RuntimeWarning: coroutine 'AddonManager.handle_lifecycle' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Process Process-1:
Traceback (most recent call last):
  File
"C:\Users\MediaLaptop\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py",
line 314, in _bootstrap
    self.run()
  File
"C:\Users\MediaLaptop\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py",
line 108, in run
    self._target(*self._args, **self._kwargs)
  File
"C:\Users\MediaLaptop\Documents\auto-southwest-check-in\lib\reservation_monitor.py",
line 42, in monitor
    self.checkin_scheduler.refresh_headers()
  File
"C:\Users\MediaLaptop\Documents\auto-southwest-check-in\lib\checkin_scheduler.py",
line 52, in refresh_headers
    webdriver.set_headers()
  File
"C:\Users\MediaLaptop\Documents\auto-southwest-check-in\lib\webdriver.py",
line 81, in set_headers
    self._quit_browser(driver)
  File
"C:\Users\MediaLaptop\Documents\auto-southwest-check-in\lib\webdriver.py",
line 244, in _quit_browser
    os.waitpid(driver.browser_pid, 0)
ChildProcessError: [Errno 10] No child processes


Let me know if you need anything else.  Log attached.

**Comment by jdholtz** [comment]
Thanks for testing quickly. This is actually an error from another change I made. Can you comment out lines 244 and 245 in `lib/webdriver.py` (add a # at the beginning of the line) and try again? Therefore, it will only test the fix for this issue.

**Comment by rbrotz69** [comment]
Hi Joey,

That worked!!  Thanks.

Once this update is official do I need to back out of any of the changes I
made?  Or will the "git pull" to do the update fix everything?

**Comment by jdholtz** [comment]
That’s great! Once v4.3 is released, you can do a couple of things to make sure the update goes smoothly:
```
$ git restore lib/webdriver.py    - Remove your changes made
$ git checkout master    -  Move back to the main branch
$ git pulll     - Update!
```

**Comment by jdholtz** [comment]
I fixed the issue you ran into earlier (and tested it on Windows), so you can actually just run `git restore lib/webdriver.py` and `git pull` to get the latest fix. From there, once v4.3 comes out, you can update by just doing `git checkout master` and `git pull`.
