### ISSUE TITLE
Clarity in README for party of >1

### ISSUE THREAD

**Issue by davidkassa** [jdholtz/auto-southwest-check-in#12]
It's unclear whether I need to run a separate instance for each individual on a reservation or whether this will auto-checkin the entire party. I'm guessing the latter. It would be nice if there were a note in the README for this.

**Comment by jdholtz** [comment]
It will check in everyone under the same reservation. I’ll add this to the README. Thanks for the suggestion.

**Comment by jdholtz** [comment]
Hey @davidkassa. I added this clarification to the README. Please let me know if this clears up any doubts related to this issue.

**Comment by davidkassa** [comment]
Perfect- thanks. Script worked flawlessly this morning too!On Sep 16, 2022, at 7:58 AM, Joey H ***@***.***> wrote:﻿
Hey @davidkassa. I added this clarification to the README. Please let me know if this clears up any doubts related to this issue.
