### ISSUE TITLE
Error during fare check

### ISSUE THREAD

**Issue by DougSisk** [jdholtz/auto-southwest-check-in#122]
### Description

Received the following error after starting up. Looks to have glitched on a reservation purchased with money. Points purchased reservation was checked just fine.

```
2023-07-14 15:40:34 ERROR Process-1[reservation_monitor:84]: Unexpected error during fare check: AttributeError("'int' object has no attribute 'replace'")
Traceback (most recent call last):
  File "/Users/doug/Code/auto-southwest-check-in/lib/reservation_monitor.py", line 78, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "/Users/doug/Code/auto-southwest-check-in/lib/fare_checker.py", line 35, in check_flight_price
    amount = int(flight_price["amount"].replace(",", ""))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'replace'
```

### To Reproduce

Fare check a reservation purchased with money

### Version

4.3

### Additional context

MacOS 13.4.1
Chrome 114.0.5735.198

**Comment by DougSisk** [comment]
Incorrectly opened the issue stating it was an issue with a point reservation; actually glitching with a money reservation

**Comment by jdholtz** [comment]
Thanks for filing this issue. Can you attach your logs? The logs show the values of the flight’s price difference so it will help me understand the context of the situation better. It should not contain any sensitive information.

**Comment by DougSisk** [comment]
[auto-southwest-check-in.log](https://github.com/jdholtz/auto-southwest-check-in/files/12053714/auto-southwest-check-in.log)

**Comment by jdholtz** [comment]
Thanks. This was a simple mistake by me. 

If you want to use the fix, you can do `git pull` and `git checkout develop`.
