### ISSUE TITLE
Did not check in for me

### ISSUE THREAD

**Issue by jdubb2** [jdholtz/auto-southwest-check-in#130]
### Description

Has worked well until today when it didn't check me in, running in docker. Nothing has changed have used successfully before

Encountered a Too Many Requests error while logging in. Skipping reservation retrieval
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/checkin_handler.py", line 68, in _set_check_in
    self._wait_for_check_in(checkin_time)
  File "/app/lib/checkin_handler.py", line 89, in _wait_for_check_in
    time.sleep(sleep_time)
ValueError: sleep length must be non-negative

### To Reproduce

Just running in docker

**Comment by jdholtz** [comment]
Thanks for filing this issue. Can you attach the full logs of the run to make it easier to debug? Also, do you continuously encounter a Too Many Requests error if you run it again? Last, what version of the script are you running?

**Comment by jdholtz** [comment]
Hey @jdubb2, any update to my previous comment? You won’t be able to run it again since the check in window has passed, but the logs would be helpful

**Comment by jdubb2** [comment]
Just got back, I rebuilt everything so no logs to add unfortunately. Worked perfectly this last time I used to check in for a flight. Will monitor and pull logs if it happens again,
