### ISSUE TITLE
checkin failure

### ISSUE THREAD

**Issue by bllfr0g** [jdholtz/auto-southwest-check-in#132]
### Version

Auto-Southwest Check-In v5.0

### Description

Failure to check in: 429 error

### To Reproduce

Use tool to attempt to checkin to flight

### Expected Behavior

Successful checkin to flight

### Relevant logs and program output

```sh
# docker logs swa
Successfully scheduled the following flights to check in for <<REDACTED>>:
Flight from <<REDACTED>>
Flight from <<REDACTED>>

Checking in to flight from <<REDACTED>

Failed to check in to flight <<REDACTED>>. Reason: Too Many Requests 429.
Check in at this url: https://mobile.southwest.com/check-in
```

**Comment by jdholtz** [comment]
Thanks for reporting this. Does this issue occur repeatedly? If so, does this issue occur with v4.3?

**Comment by jdholtz** [comment]
Hey @bllfr0g, any update to my previous comment? Since the check-in window has passed, it might not be possible to debug this issue but providing the logs (found in the `logs` directory) would be helpful.

**Comment by bllfr0g** [comment]
Sorry. Trip is over and I don't have another southwest flight planned.

**Comment by jdholtz** [comment]
Sounds good. If you or someone else runs into this issue again, I can reopen this.

**Comment by agentdr8** [comment]
Tried checking in for my son's upcoming flight, and ran into the "429 too many requests" error. This was on v5.1 of the master branch. I then switched to the selenium_base branch, refreshed requirements, and tried to run it again and even though he's already checked in to his arrival flight, it still comes back with the 429 error. Logs attached. 

[master_log.txt](https://github.com/jdholtz/auto-southwest-check-in/files/12703223/master_log.txt)
[selenium_base_log.txt](https://github.com/jdholtz/auto-southwest-check-in/files/12703224/selenium_base_log.txt)
