### ISSUE TITLE
Webdriver timeout in container

### ISSUE THREAD

**Issue by stcbus** [jdholtz/auto-southwest-check-in#147]
### Version

5.1

### Description

I upgraded to the latest version and now when I run the docker the log shows no output and I have a flight on Wednesday. Adding my reservation directly instead of just account shows no change. I have notification level set to 1.

### To Reproduce

Get latest docker version
Add account to southwest.json config file with an upcoming flight.
Run

### Expected Behavior

It should notice my flights and alert me when its scheduled right?

### Relevant logs and program output

```sh
/app/logs # tail auto-southwest-check-in.log
2023-09-11 15:33:43 DEBUG MainProcess[config:83]: Using 1 notification services
2023-09-11 15:33:43 DEBUG MainProcess[config:87]: Setting retrieval interval to 24 hours
2023-09-11 15:33:43 DEBUG MainProcess[config:121]: Creating configurations for 1 accounts
2023-09-11 15:33:43 DEBUG MainProcess[config:128]: Creating configurations for 1 reservations
2023-09-11 15:33:43 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 1 reservations
2023-09-11 15:33:43 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-09-11 15:33:43 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-09-11 15:33:43 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-09-11 15:33:43 DEBUG Process-1[webdriver:146]: Starting webdriver for current session
2023-09-11 15:33:43 DEBUG Process-2[reservation_monitor:60]: Acquiring lock...
```

**Comment by jdholtz** [comment]
Hi. Thanks for filing this issue. It appears that the webdriver never actually starts correctly. Does it show any more logs or tracebacks using `docker logs`? 

By the way, you can also run the image with the `--verbose` flag at the very end to see debug messages with `docker logs`.

**Comment by jdholtz** [comment]
This is the same issue that was in #96. People reported that adding the privileged flag to the docker container (I believe right after the `run` word) fixed the issue for them. Does adding the `--privileged` flag work for you?

**Comment by stcbus** [comment]
duhh, yes that does fix it.

**Comment by jdholtz** [comment]
Good to hear. However, that isn't the ideal solution since that makes the container run as a privileged user.

If you have time, it would be great if you could try to edit the `/etc/hosts` file instead of running the container with `--privileged`.
1. Override the Docker entrypoint to run it forever: `docker run --entrypoint sleep jdholtz:auto-southwest-check-in infinity`
2. Exec into the container: `docker exec -it <container-name> sh`
3. Add the following to `/etc/hosts` using `vi /etc/hosts`:
```
127.0.0.1       localhost.localdomain   localhost
::1             localhost.localdomain   localhost
```
If you don't know how to use vi (vim), press `i` to be in insert mode. Then paste the text in (Ctrl+Shift+V on my machine). To save and quit, press `<Esc>` and type `:wq`.
4. Run the script manually doing `python southwest.py <Arguments> --verbose`

**Comment by StevenMassaro** [comment]
For what it's worth, I am running this in docker compose and it only works when I add:
```
    cap_add:
      - SYS_ADMIN
```

**Comment by jdholtz** [comment]
SYSM_ADMIN gives administrator privileges to the container, so it still isn’t ideal. Does adding `--network=host` to the Docker run command solve the issue? If not, you can try my suggestions [here](https://github.com/jdholtz/auto-southwest-check-in/issues/96#issuecomment-1606151852) to see if it is a Selenium issue with Docker, not just with this script. I’m unable to produce that issue, so I am of little help in debugging this issue.

**Comment by StevenMassaro** [comment]
I just removed the sys admin permission and it still works. Weird.

**Comment by jdholtz** [comment]
> I just removed the sys admin permission and it still works. Weird.

Yeah, people reported that they only had issues for about a month or two at me it started working again. I’ll close this since it seems to be a rare issue that has a workaround (although not the most ideal) and eventually fixes itself (?).

**Comment by jdholtz** [comment]
To note, I did change browser frameworks in the [selenium_base](https://github.com/jdholtz/auto-southwest-check-in/tree/selenium_base) branch, so hopefully that will fix issues like this one. Once I get verification from others that it works well, it will be part of the next release.
