### ISSUE TITLE
OpenSSL.SSL' has no attribute

### ISSUE THREAD

**Issue by stgreenb** [jdholtz/auto-southwest-check-in#15]
Issue came in: 

  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 43, in <module>
    "SSLv2": (SSL.SSLv2_METHOD, BASIC_OPTIONS),
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'. Did you mean: 'SSLv23_METHOD'

Solved with: pip install pyopenssl==22.0.0

**Comment by jdholtz** [comment]
Hey. This was a problem with seleniumwire. Updating it to 5.0.0 works to fix the pyopenssl version error. I fixed this on the another branch, so I will merge the change later today.
