### ISSUE TITLE
Flight Didn't Check In & Notifications Not Sending

### ISSUE THREAD

**Issue by rsokz** [jdholtz/auto-southwest-check-in#156]
### Version

5.1

### Description

Hey - first time giving your product a try. I successfully logged into my southwest account the other day and set up check in for multiple upcoming flights. First check in was today but never went through. I decided to set up notifications for upcoming flights. I've tried with SNS and simple mailto. The command line shows the following but test notification doesn't come through.

```
Sending test notifications to 2 sources
This is a test message
```

Config file looks like this (details from urls omitted):
```
{
    "check_fares": true,
    "notification_urls": [
        "sns://AccessKeyID/AccessSecretKey/RegionName/+PhoneNo,
        "mailto://userid:pass@gmail.com"
    ],
    "notification_level": 1,
    "retrieval_interval": 24,
    "accounts": [],
    "reservations": []
}
```

One thing to note is I'm on the selenium_base branch due to chrome version issues. 

### To Reproduce

1. python3 southwest.py --test-notifications

### Additional context

Chrome Version 117.0.5938.88
Python 3.8.9
MacOS 13.3.1

**Comment by jdholtz** [comment]
Thanks for reporting this. You probably aren’t getting notifications because your URLs are not correct. You can test your URLs directly with Apprise (refer to the documentation [here](https://github.com/caronc/apprise) and modify them according to the Apprise documentation if they don’t work. 

Could you send the log file of your failed check-in?

**Comment by rsokz** [comment]
Probably the answer and a simple question... does the script need to be running up til the point of the check in? If it's killed, check in won't work, correct?

**Comment by jdholtz** [comment]
> If it's killed, check in won't work, correct?

Yes, that is correct. Also, it doesn’t work if your computer goes to sleep while the script is running (you will need to restart the script in this case).

**Comment by jdholtz** [comment]
Were you able to get the notification URLs working?
