### ISSUE TITLE
Run with sudo?

### ISSUE THREAD

**Issue by schmeed** [jdholtz/auto-southwest-check-in#16]
Not an issue, but easiest way to ask a question.  Should the .py script be run using sudo?  Or regular user?

I have a flight upcoming on Saturday so I'll let you know how it works.

Thanks!
Dave

**Comment by jdholtz** [comment]
You should be able to run it with or without sudo (as long as the regular user has permissions to read/run the files). However, I don’t recommend running it with sudo, as there is no reason to, so it would only provide potential security issues.

**Comment by schmeed** [comment]
Makes perfect sense.  Thank you!
