### ISSUE TITLE
Missing flight number and/or confirmation number in V6.1 request for check-in

### ISSUE THREAD

**Issue by dpbraune** [jdholtz/auto-southwest-check-in#164]
### Version

6.1

### Description

V6.1 upgrades smoothly but the confirmation number is now missing and the flight number feature does not seem to work.

### To Reproduce

Simply request a flight check-in

### Expected Behavior

Expected the reply to include the flight number as stated in the CHANGE.LOG and possibly the confirmation number as displayed in earlier versions.

### Relevant logs and program output

```sh
D:\auto-southwest-check-in>python southwest.py
Successfully scheduled the following flights to check in for XXXXX YYYYYY:
Flight from Denver to Chicago (Midway) at 2023-10-04 00:40:00 UTC
```

**Comment by jdholtz** [comment]
Hi. Thanks for reporting this. 

> confirmation number is now missing 

The confirmation number was never shown, at least not in the output you displayed.

Here is the output for v5.1 (v6.0 is the same):
```
Successfully scheduled the following flights to check in for X X:
Flight from X to X at <Date> <Time> UTC
```
Here is the output for v6.1:
```
Successfully scheduled the following flights to check in for X X:
Flight from X to X at <Date> <Time> UTC
```

> Expected the reply to include the flight number as stated in the CHANGE.LOG

The changelog simply stated that flight numbers are used to identify flights, but they won't be reported to the user as I don't think seeing the flight number would give any helpful information (most people don't know or care about their flight number).

**Comment by jdholtz** [comment]
I’ll close this issue since it seems that everything is working as expected. I can reopen this if you have any more suggestions about outputting this information.
