### ISSUE TITLE
Config file not appearing in v6.1 Docker container

### ISSUE THREAD

**Issue by texrodin** [jdholtz/auto-southwest-check-in#167]
### Version

6.1

### Description

I have built the new docker file using v6.1 -- the config.json file doesn't appear to be found, so using default, even though config.json is in the root directory.  I'm not sure if the flight notifications work because I don't have a flight till later in the month.

### To Reproduce

I am running the --test-notifications option, which works in my last build of the 4.1

### Relevant logs and program output

```sh
2023-10-03 13:36:04 DEBUG MainProcess[log:23]: Initialized the application
2023-10-03 13:36:04 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-03 13:36:04 DEBUG MainProcess[main:113]: Called with 1 arguments
2023-10-03 13:36:04 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-03 13:36:04 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-03 13:36:04 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-10-03 13:36:04 INFO MainProcess[main:85]: Sending test notifications to 0 sources
```

### Additional context

Here's my config.json file for v6.1:
{
    "check_fares": true,
    "notification_urls": "twilio://aaa:bbb@1xxxxxxxxxx/1xxxxxxxxxx",
    "notification_level": 1,
    "retrieval_interval": 24,
    "accounts": [],
    "reservations": []
}

**Comment by texrodin** [comment]
@jdholtz On the other versions, I never mounted the config file, it just seemed to work.  On this version, I did mount it as you suggested in the Readme, and got it to work that way, but this is a new change from previous versions.  Not sure if that helps?

C:\Users\txr\Desktop\swa\auto-southwest-check-in-6.1>docker run -d --volume C:\Users\txr\Desktop\swa\auto-southwest-check-in-6.1\config.json:/app/config.json auto-southwest-check-in --test-notifications

when I use v4.1, I just run: docker run -d auto-southwest-check-in --test-notifications, and notifications work.

**Comment by jdholtz** [comment]
> On the other versions, I never mounted the config file, it just seemed to work

Were you using the official Docker image? That doesn't include a config.json. In v6.0, I did add the `config.json` to the `.dockerignore` so it wouldn't be included in the image (could introduce unexpected vulnerabilities if someone shares the image and accidentally includes the config.json). It was never supposed to work as it did before v6.0, that was a mistake on my part.

You can remove `config.json` from the `.dockerignore` or just mount it as you did.

**Comment by jdholtz** [comment]
> Here you go. I have discord as the configured notification agent.

Does `--test-notifications` work for you? If not, try following the [Apprise Command Line Usage](https://github.com/caronc/apprise#command-line-usage) section to see if your URL is actually correct

**Comment by thefirstnoe1** [comment]
> > Here you go. I have discord as the configured notification agent.
> 
> Does `--test-notifications` work for you? If not, try following the [Apprise Command Line Usage](https://github.com/caronc/apprise#command-line-usage) section to see if your URL is actually correct

Am dumb, had a type in --test-notifications. Fixed that and my notifications are working! Thanks for the quick response and the awesome work done on this.

**Comment by jdholtz** [comment]
Great to hear. Thank you!
