### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'

### ISSUE THREAD

**Issue by cmclinton** [jdholtz/auto-southwest-check-in#169]
### Version

6.1

### Description

fresh git pull and fresh pip install -r requirements.txt

then...python3 southwest.py [username] [password]

### To Reproduce

python3 southwest.py [username] [password]

### Relevant logs and program output

```sh
python3 southwest.py [username] [password]

Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 117.0.5938.92 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip ...

*** chromedriver to download = 117.0.5938.92 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip ...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
  File "/home/cclinton/auto-southwest-check-in/lib/reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
  File "/home/cclinton/auto-southwest-check-in/lib/webdriver.py", line 133, in _get_driver
    driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
```

**Comment by cmclinton** [comment]
Initial test was on WSL running Ubuntu 22.04.03 running on WSL. I also just tried the code on Windows 11 CMD prompt and received the exact same error message as above.

**Comment by jdholtz** [comment]
> AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'

The object should actually be named 'Chrome', so that is weird. Can you execute the following in a Python terminal (type `python` in your virtual environment) and report what the output is?

```py
from seleniumbase import Driver
driver = Driver(undetectable=True, headless=True)
type(driver)  # <-- for me, this is 'seleniumbase.undetected.Chrome'
```

**Comment by cmclinton** [comment]
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from seleniumbase import Driver
>>> driver = Driver(undetectable=True, headless=True)

Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 117.0.5938.92 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip ...

*** chromedriver to download = 117.0.5938.92 (Latest Stable)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip ...
>>> type(driver)
<class 'selenium.webdriver.chrome.webdriver.WebDriver'>
>>>

**Comment by jdholtz** [comment]
It may not be downloading the driver correctly. In your virtual environment, can you execute `sbase get uc_driver` and then see if the script works then? If not, try `sbase get chromedriver` and test the script again.

**Comment by cmclinton** [comment]
It tried multiple times and then I received an SSL error

'''
requests.exceptions.SSLError: HTTPSConnectionPool(host='edgedl.me.gvt1.com', port=443): Max retries exceeded with url: /edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
'''

**Comment by jdholtz** [comment]
> It tried multiple times and then I received an SSL error

Could you try the solution [here](https://github.com/Rapptz/discord.py/issues/5968#issuecomment-716222434) to see if it fixes your issue?

**Comment by cmclinton** [comment]
I tried the fix you suggested and then re-ran sbase get chromedriver. I again get SSL errors.

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='edgedl.me.gvt1.com', port=443): Max retries exceeded with url: /edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
```

**Comment by jdholtz** [comment]
My suggestion would be to make an issue in the [SeleniumBase](https://github.com/seleniumbase/SeleniumBase) repository, since it can be reproduced without using this script at all.

**Comment by jdholtz** [comment]
Hey @cmclinton, do you have any updates to my previous comment?

**Comment by cmclinton** [comment]
Hey - I tried 6.1 on an Amazon EC2 instance and it worked fine, so I'm pretty certain that the issue is something with our network and not with your code.

**Comment by jdholtz** [comment]
> Hey - I tried 6.1 on an Amazon EC2 instance and it worked fine, so I'm pretty certain that the issue is something with our network and not with your code.

Sounds good. If you have any more issues with this or found a fix that includes modifying this repository, I can open this again. Thanks for helping debug.
