### ISSUE TITLE
Chrome version mismatch causes Too Many Requests

### ISSUE THREAD

**Issue by wrusry** [jdholtz/auto-southwest-check-in#172]
### Version

Auto-Southwest Check-In v6.1

### Description

Hello, I had the failure in v 6.0 of too many requests on my outbound checkin. So, I upgraded to version 6.1 to try to use it to check in for my return flight on my computer which doesn't go to sleep and has a UPS to it. It also failed for "too many requests". See the below image. Previously, I had used southwest.py successfully, but I had the issue of matching my chrome with your version, so in my last successful usage, I had to downgrade my Chrome browser in order to make it work. I was excited to see that the program was no longer dependent on the Chrome version. Please let me know if you need any more info from my for troubleshooting purposes.

![image](https://github.com/jdholtz/auto-southwest-check-in/assets/44855611/fa568221-8eea-4cc3-b03d-91fc2403a862)

### To Reproduce

1. Run Python southwest.py confirmationcode first_name last_name

### Expected Behavior

I expected that it would check me in. Instead I got the error: Failed to check in for flight confirmationcode for first last. Reason: Too Many Requests 429. 

You can see from my version that I am using v 6.1.

My coding skills are rough at best, so forgive any incorrect formatting of this bug report.

**Comment by jdholtz** [comment]
Hey, thanks for filing this issue. What is the Chrome version you are using?

I see that your flight is no longer valid to check in. Do you get a 429 error when you log in?

**Comment by wrusry** [comment]
I am using Chrome version 117.0.X

This is what get when I log in. 

![image](https://github.com/jdholtz/auto-southwest-check-in/assets/44855611/6aaff7e1-a5a9-4f42-ad46-c4fe373ef4fd)

**Comment by dmytrokoren** [comment]
@wrusry I had the same issue. Make sure that you are not on VPN. Southwest is blocking VPN Ip's now, and throwing 429 error too much requests.

**Comment by wrusry** [comment]
I'm not on a VPN. Thanks, though.

I just relaunched my Google Chrome browser and it updated to version 118 and I tried logging in and it appears to work. I don't know why. It downloaded chromedriver it appears.  
![image](https://github.com/jdholtz/auto-southwest-check-in/assets/44855611/1b38afe9-00e5-41be-8890-39ff9622307b)

**Comment by dmytrokoren** [comment]
> I'm not on a VPN. Thanks, though.
> 
> 
> 
> I just relaunched my Google Chrome browser and it updated to version 118 and I tried logging in and it appears to work. I don't know why. It downloaded chromedriver it appears.  
> 
> ![image](https://github.com/jdholtz/auto-southwest-check-in/assets/44855611/1b38afe9-00e5-41be-8890-39ff9622307b)
> 
> 

Glad it's working now. Sometimes a restart/relaunch solves issues.

**Comment by jdholtz** [comment]
> I just relaunched my Google Chrome browser and it updated to version 118 and I tried logging in and it appears to work. I don't know why. It downloaded chromedriver it appears

It may have been a version mismatch that ended up resulting in you being detected. SeleniumBase has an option to set the driver version to match the browser, but it is currently not working in undetected mode (it is still headed when headless is specified). 

I filed an issue on the SB repository, so when that is fixed, I will specify that when initializing the driver in this script. Then, it should ensure a version mismatch is never a problem.

**Comment by jdholtz** [comment]
Fixed in the latest commit of the develop branch. Will be part of either v6.2 or v7.0
