### ISSUE TITLE
Getting some kind of errors after successful check-in (Need your input)

### ISSUE THREAD

**Issue by dmytrokoren** [jdholtz/auto-southwest-check-in#178]
### Version

6.1

### Description

As reading from bottom to the top you can see the errors

### To Reproduce

Run the script
all is well
after successful check-in
the errors are thrown

### Expected Behavior

should be no errors...

### Additional context

<!DOCTYPE html>
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<h2>Auto-Southwest-Check-In</h2>
<table>
<tr><th>date</th><th>stream</th><th>content</th></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>requests.exceptions.ReadTimeout:&nbsp;HTTPSConnectionPool(host='mobile.southwest.com',&nbsp;port=443):&nbsp;Read&nbsp;timed&nbsp;out.&nbsp;(read&nbsp;timeout=None)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ReadTimeout(e,&nbsp;request=request)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/requests/adapters.py",&nbsp;line&nbsp;532,&nbsp;in&nbsp;send
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;r&nbsp;=&nbsp;adapter.send(request,&nbsp;**kwargs)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/requests/sessions.py",&nbsp;line&nbsp;703,&nbsp;in&nbsp;send
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;resp&nbsp;=&nbsp;self.send(prep,&nbsp;**send_kwargs)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/requests/sessions.py",&nbsp;line&nbsp;589,&nbsp;in&nbsp;request
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;session.request(method=method,&nbsp;url=url,&nbsp;**kwargs)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/requests/api.py",&nbsp;line&nbsp;59,&nbsp;in&nbsp;request
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;request("get",&nbsp;url,&nbsp;params=params,&nbsp;**kwargs)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/requests/api.py",&nbsp;line&nbsp;73,&nbsp;in&nbsp;get
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;response&nbsp;=&nbsp;requests.get(url,&nbsp;headers=headers,&nbsp;params=info)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/lib/utils.py",&nbsp;line&nbsp;31,&nbsp;in&nbsp;make_request
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;response&nbsp;=&nbsp;make_request("GET",&nbsp;site,&nbsp;headers,&nbsp;info)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/lib/checkin_handler.py",&nbsp;line&nbsp;139,&nbsp;in&nbsp;_check_in
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self._check_in()
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/app/lib/checkin_handler.py",&nbsp;line&nbsp;73,&nbsp;in&nbsp;_set_check_in
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self._target(*self._args,&nbsp;**self._kwargs)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/multiprocessing/process.py",&nbsp;line&nbsp;108,&nbsp;in&nbsp;run
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self.run()
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/multiprocessing/process.py",&nbsp;line&nbsp;314,&nbsp;in&nbsp;_bootstrap
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>During&nbsp;handling&nbsp;of&nbsp;the&nbsp;above&nbsp;exception,&nbsp;another&nbsp;exception&nbsp;occurred:
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>urllib3.exceptions.ReadTimeoutError:&nbsp;HTTPSConnectionPool(host='mobile.southwest.com',&nbsp;port=443):&nbsp;Read&nbsp;timed&nbsp;out.&nbsp;(read&nbsp;timeout=None)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ReadTimeoutError(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;370,&nbsp;in&nbsp;_raise_timeout
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self._raise_timeout(err=e,&nbsp;url=url,&nbsp;timeout_value=conn.timeout)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;469,&nbsp;in&nbsp;_make_request
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;new_e
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;491,&nbsp;in&nbsp;_make_request
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;response&nbsp;=&nbsp;self._make_request(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;790,&nbsp;in&nbsp;urlopen
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;value
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/util/util.py",&nbsp;line&nbsp;39,&nbsp;in&nbsp;reraise
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;reraise(type(error),&nbsp;error,&nbsp;_stacktrace)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py",&nbsp;line&nbsp;470,&nbsp;in&nbsp;increment
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;retries&nbsp;=&nbsp;retries.increment(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;844,&nbsp;in&nbsp;urlopen
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;resp&nbsp;=&nbsp;conn.urlopen(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/requests/adapters.py",&nbsp;line&nbsp;486,&nbsp;in&nbsp;send
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>The&nbsp;above&nbsp;exception&nbsp;was&nbsp;the&nbsp;direct&nbsp;cause&nbsp;of&nbsp;the&nbsp;following&nbsp;exception:
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>TimeoutError:&nbsp;[Errno&nbsp;110]&nbsp;Operation&nbsp;timed&nbsp;out
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self._sslobj.do_handshake()
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/ssl.py",&nbsp;line&nbsp;1379,&nbsp;in&nbsp;do_handshake
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self.do_handshake()
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/ssl.py",&nbsp;line&nbsp;1108,&nbsp;in&nbsp;_create
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.sslsocket_class._create(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/ssl.py",&nbsp;line&nbsp;517,&nbsp;in&nbsp;wrap_socket
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ssl_context.wrap_socket(sock,&nbsp;server_hostname=server_hostname)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py",&nbsp;line&nbsp;513,&nbsp;in&nbsp;_ssl_wrap_socket_impl
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;ssl_sock&nbsp;=&nbsp;_ssl_wrap_socket_impl(sock,&nbsp;context,&nbsp;tls_in_tls,&nbsp;server_hostname)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py",&nbsp;line&nbsp;469,&nbsp;in&nbsp;ssl_wrap_socket
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;ssl_sock&nbsp;=&nbsp;ssl_wrap_socket(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connection.py",&nbsp;line&nbsp;783,&nbsp;in&nbsp;_ssl_wrap_socket_and_match_hostname
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;sock_and_verified&nbsp;=&nbsp;_ssl_wrap_socket_and_match_hostname(
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connection.py",&nbsp;line&nbsp;642,&nbsp;in&nbsp;connect
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;conn.connect()
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;1092,&nbsp;in&nbsp;_validate_conn
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;&nbsp;&nbsp;self._validate_conn(conn)
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>&nbsp;&nbsp;File&nbsp;"/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py",&nbsp;line&nbsp;467,&nbsp;in&nbsp;_make_request
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
</td></tr>
<tr><td>2023/11/04&nbsp;21:05:31</td><td>stdout</td><td>Process&nbsp;Process-1:1:
</td></tr>
<tr><td>2023/11/04&nbsp;20:50:09</td><td>stdout</td><td>
</td></tr>
<tr><td>2023/11/04&nbsp;20:50:09</td><td>stdout</td><td>Successfully&nbsp;checked&nbsp;in&nbsp;to&nbsp;flight&nbsp;from&nbsp;'aaa&nbsp;()'&nbsp;to&nbsp;'bbb&nbsp;()'&nbsp;for&nbsp;FN&nbsp;LN!
</td></tr>
</table></body></html>

**Comment by jdholtz** [comment]
It looks like the request timed out and raised the error. Is this a repeatable error? If so, I can handle it explicitly. Otherwise, I wouldn’t really worry about it as it didn’t affect the check-in process at all and seems like a very rare bug (in the sense that no one has seen this issue before you).

**Comment by dmytrokoren** [comment]
> It looks like the request timed out and raised the error. Is this a repeatable error? If so, I can handle it explicitly. Otherwise, I wouldn’t really worry about it as it didn’t affect the check-in process at all and seems like a very rare bug (in the sense that no one has seen this issue before you). 

This error occurs when the request times out because I left it running for like few hours after it was successfully checked in. I don't know how difficult it is to debug and handle it explicitly but it would be nice to have a clean log afterwards :)

**Comment by jdholtz** [comment]
> This error occurs when the request times out because I left it running for like few hours after it was successfully checked in

It looked like it occurred before the check-in though, but no errors should be thrown if the script continues running after a successful check-in.

> I don't know how difficult it is to debug and handle it explicitly

It isn't very hard. I would just make it so it ignores the error and tries again. I was just wondering if it was worth it do so if this error has only ever happened once (no one else has reported this before).

**Comment by dmytrokoren** [comment]
> > This error occurs when the request times out because I left it running for like few hours after it was successfully checked in
> 
> 
> 
> It looked like it occurred before the check-in though, but no errors should be thrown if the script continues running after a successful check-in.
> 

![image](https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/8a2dc252-0c67-4326-94c5-a1b30f4eaa00)

The log is actually inverted so the latest is at the top.
Successfully message came at 20:50
And the errors started at 21:05

> > I don't know how difficult it is to debug and handle it explicitly
> 
> 
> 
> It isn't very hard. I would just make it so it ignores the error and tries again. I was just wondering if it was worth it do so if this error has only ever happened once (no one else has reported this before).

If that's worth your time that would be nice if not leave it. I guess users didn't encounter this because they didn't leave the script running for this long after they were checked in, that's what I think.

**Comment by jdholtz** [comment]
> The log is actually inverted so the latest is at the top.

Ah, I did not see that.

>  I guess users didn't encounter this because they didn't leave the script running for this long after they were checked in, that's what I think.

I've left the script running for more than 12 hours after the check-in (and some people leave it running until the script exits itself), so this error shouldn't still happen. 

Could you send the verbose logs of the script for this run? It can be found in the `/app/logs/` directory of the container. I'm interested to see how this timeout occurred.

**Comment by dmytrokoren** [comment]
> Could you send the verbose logs of the script for this run? It can be found in the `/app/logs/` directory of the container. I'm interested to see how this timeout occurred. 

I will send that asap. I have to find it in docker first. I'll keep you posted.

**Comment by dmytrokoren** [comment]
@jdholtz v7.0 fixed it since I guess it was updated to python 3.12 - so I'm closing this issue as I re-tested it and no errors is coming after 15 min of successful check-in.

**Comment by jdholtz** [comment]
Oh, awesome. Let me know if it comes up again and I’ll see how it can be handled
