### ISSUE TITLE
Adding a Docker container to run in the background? 

### ISSUE THREAD

**Issue by adyotag** [jdholtz/auto-southwest-check-in#18]
This could be a nice feature to add in the future... It also avoids issues with dependencies across different systems as everything is standardized under the container.

**Comment by jdholtz** [comment]
Thanks for the request! I plan to implement this by the end of the year, but hopefully sooner if I have time. Feel free to help contribute towards this if you want.

**Comment by sdstolworthy** [comment]
I'll see if I can't take a whack at that next week. I'll have a couple hours of free time.

**Comment by adyotag** [comment]
> I'll see if I can't take a whack at that next week. I'll have a couple hours of free time.

I'd love to help out as well!

**Comment by sdstolworthy** [comment]
@adyotag and @jdholtz just put up a PR for your review
