### ISSUE TITLE
chomrdriver not installing / working?

### ISSUE THREAD

**Issue by clwclw123** [jdholtz/auto-southwest-check-in#194]
### Version

Auto-Southwest Check-In v7.1

### Browser Version

120.0.6099.115 (Brave)

### Description

Updated to 7.1 and now I'm getting this error

```
Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 120.0.6099.109 (Latest Stable)

Downloading chromedriver-win64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...

DevTools listening on ws://127.0.0.1:55324/devtools/browser/0567ff57-7d0e-4ff6-94d2-1ee336fe2e2a
2023-12-18 16:19:34 DEBUG Process-1[webdriver:119]: Using browser version: 120.0.6099.72
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\webdriver.py", line 77, in get_reservations
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\webdriver.py", line 121, in _get_driver
    driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
Press any key to continue . . .

```

### To Reproduce

python3 southwest.py --verbose

### Additional context

I'm sure im doing something wrong but I can't seem to figure it out

**Comment by jdholtz** [comment]
This is a similar issue to #186. Can you do `sbase get uc_driver` and then run the script and paste the output here (of both the command and the script’s run)? Also, I believe you need to use [browser_path config option](https://github.com/jdholtz/auto-southwest-check-in/blob/master/CONFIGURATION.md#browser-path) if you are using Brave.

**Comment by jdholtz** [comment]
> but deleting chromedriver.exe in that path worked.

Awesome. Is the issue resolved now?

> for browser_path how would I give it a windows path?

Putting this in my config.json works:
```json
{
    "browser_path": "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"
}
```

**Comment by jdholtz** [comment]
> Though for future enhancements maybe I can help you troubleshoot to figure out a way to get/set the right perms to replace chromedriver.exe?

This is all handled by [SeleniumBase](https://github.com/seleniumbase/SeleniumBase) so if you run into an issue with it without using this script at all (e.g. using the `sbase` command) it would be great if you could file an issue on that repository.

> additionally that browser path does work, but it is specifically looking for chrome.exe / anyway to make it accept brave.exe as well?

Thanks for letting me know. I’ll look into this

**Comment by jdholtz** [comment]
> additionally that browser path does work, but it is specifically looking for chrome.exe / anyway to make it accept brave.exe as well?

I believe what was happening is that you have Chrome installed on your system as well and the script used that. Upgrading to SeleniumBase 4.22.1 will allow you to specify the `brave.exe` file in the config. It is still necessary, though, as SeleniumBase doesn't find the brave executable by default.

**Comment by jdholtz** [comment]
> Any idea what to try?

Did you do `pip install -r requirements.txt` after updating the file? You still must be using the wrong version because the list of exe files has been updated in SB 4.22.1 ([evidence](https://github.com/seleniumbase/SeleniumBase/blob/77c0ccde3d299a2d680f339404bb0cb050ebf62e/seleniumbase/fixtures/constants.py#L412)).
