### ISSUE TITLE
Check in failed with error: Too Many Requests 429

### ISSUE THREAD

**Issue by grantland** [jdholtz/auto-southwest-check-in#21]
I got a failure last night attempting to try this project for the first time using Docker. FWIW this was an international flight and it required our passport information when checking in manually.

```
$ docker logs 1234
Scheduling checkin to flight from 'X' to 'Y' for John Smith at 2022-11-11 12:59:55 UTC

Scheduling checkin to flight from 'Y' to 'X' for John Smith at 2022-11-15 21:59:55 UTC

Checking in to flight from 'X' to 'Y' for John Smith

Failed to check in to flight FOOBAR for John Smith. Reason: Too Many Requests 429.
Check in at this url: https://mobile.southwest.com/check-in
```

**Comment by jdholtz** [comment]
Hey. Thanks for filing this issue! I had an international flight a few days ago and I got the same result. It could probably be detected within the script, but I don't have another international flight anytime soon, so I am not able to test that. 

What could work is automatically filling that information out within the script, but that doesn't seem like a good idea. Unless you have any ideas, I'll probably just add a note to the README that indicates the script only works with domestic flights.

By the way, did it still seem like the check in went through (i.e. you still got a really good boarding position) even though it threw an error?

**Comment by jdholtz** [comment]
Hey @grantland. Did you know if you filled out your passport information beforehand? If not, that is what most likely caused the error. Could you try the script again for the return flight and see if it works? Thanks!

**Comment by grantland** [comment]
> Hey. Thanks for filing this issue! I had an international flight a few days ago and I got the same result. It could probably be detected within the script, but I don't have another international flight anytime soon, so I am not able to test that.

> What could work is automatically filling that information out within the script, but that doesn't seem like a good idea. Unless you have any ideas, I'll probably just add a note to the README that indicates the script only works with domestic flights.

This seems like a good idea for now and maybe detection in the script that also warns the user via a notification if they attempt to schedule an international flight

> By the way, did it still seem like the check in went through (i.e. you still got a really good boarding position) even though it threw an error?

Nope it did not successfully check in

> Hey @grantland. Did you know if you filled out your passport information beforehand? If not, that is what most likely caused the error. Could you try the script again for the return flight and see if it works? Thanks!

I'm not sure about the first time and the second time didn't run since my machine restarted and I forgot `--restart unless-stopped`

**Comment by jdholtz** [comment]
Unfortunately I don’t have any international flights to test with, so I’ll just add that note saying to fill out passport information before international flight check ins. After that I’ll close this issue. 

If there’s still a problem with international even when passport info was filled out, I’ll add a note saying that the script only works for domestic flights.
