### ISSUE TITLE
Fare check lower price with same day option

### ISSUE THREAD

**Issue by FlynnJoe** [jdholtz/auto-southwest-check-in#212]
### Description

The fare check is a great feature. Thank you for all your efforts.
An option to notify if there is lower fare for the route being checked the same day (not just the same flight). When changing flights in the app it shows all the prices for the day.  Assume this is the source of the pricing data. 
This option could be useful for those with flexible travel plans and those with A-list. 

“check_fares”: true,
“report_lower_fare_same_day”: true,

Default with no same day option would be existing behavior, report for the same flight only. 

### What alternatives have you considered?

Manual check only

**Comment by jdholtz** [comment]
Thanks for this feature request! I like it and it won't be hard to implement. Would you prefer to have a separate config value for this, or something like `check_fares: "same_day"` to check all fares for the same day and `check_fares: "yes"` (or "no". Would accept all truthy values to keep the compatibility)?

**Comment by FlynnJoe** [comment]
Hi Joey - whatever is easiest for you to implement. Thanks!On Jan 29, 2024, at 7:10 PM, Joey Holtzman ***@***.***> wrote:﻿
Thanks for this feature request! I like it and it won't be hard to implement. Would you prefer to have a separate config value for this, or something like check_fares: "same_day" to check all fares for the same day and check_fares: "yes" (or "no". Would accept all truthy values to keep the compatibility)?

**Comment by FlynnJoe** [comment]
﻿﻿Hi Joey - whatever is easiest for you to implement. Thanks!On Jan 29, 2024, at 7:10 PM, Joey Holtzman ***@***.***> wrote:﻿
Thanks for this feature request! I like it and it won't be hard to implement. Would you prefer to have a separate config value for this, or something like check_fares: "same_day" to check all fares for the same day and check_fares: "yes" (or "no". Would accept all truthy values to keep the compatibility)?

**Comment by jdholtz** [comment]
How do you propose to notify if there are multiple flights found to have lower fares? Would it just be the first one found, the lowest fare, something else? What makes the most sense to me is the lowest fare, but want to get your input on what you were thinking for this feature.

**Comment by FlynnJoe** [comment]
I agree with you, my thinking lowest fare only since a text via Apprise is 160 chars. On Feb 4, 2024, at 12:18 PM, Joey Holtzman ***@***.***> wrote:﻿
How do you propose to notify if there are multiple flights found to have lower fares? Would it just be the first one found, the lowest fare, something else? What makes the most sense to me is the lowest fare, but want to get your input on what you were thinking for this feature.

**Comment by dmytrokoren** [comment]
@jdholtz sorry if wrong topic. Is there already an option to get notification via apprise for fare change if lower fare found?

**Comment by davidkassa** [comment]
How do you handle flights with multiple legs?

**Comment by babehboi** [comment]
Just wanted to chime in on some configuration options if available:

To be able to choose between the lowest fare tracking any or all flights or just your flight number because sometimes the lowest fare might not always be a nonstop that you may have preferred.

1st flight found versus lowest fare may be inconsequential since you will see all at the time of login? But could be useful for some.

@davidkassa - do you mean when it's not a nonstop flight? Because today if you have multiple legs it just checks your flight number. If you have separate reservations for each of the legs then the script will pick them up anyways?

**Comment by davidkassa** [comment]
yes, I meant nonstop

**Comment by FlynnJoe** [comment]
Would an enumeration with the following choices cover the options requested and presented by Southwest API?

class check_fare_option(enum.IntEnum):
    no = 0x1
    same_flight = 0x2
    same_day_any = 0x4
    same_day_nonstop = 0x8
    def __str__(self):
        return ‘%s’ % self.name

Continuing below is forward looking in case someone with very flexible plans might appreciate using the script to search around the date as well:

    within_one_day_any = 0x10
    within_one_day_nonstop = 0x20
    within_three_days_any = 0x40
    within_three_days_nonstop = 0x80

Thinking about the notification:
If *any  is selected,  notification can send price deltas to original flight, lowest nonstop, and lowest connecting (if <  -$1).
If *nonstop is selected, send price delta to original flight and lowest cost nonstop flight. 

Currently the apprise text notification contains the origin, destination, confirmation #, and hyperlink.  
Suggest adding the date as my use case repeats the same route many times, which leads to searching all reservations to match the confirmation.

**Comment by jdholtz** [comment]
> Would an enumeration with the following choices cover the options requested and presented by Southwest API?

Those four configuration options seem plausible. Would having a difference between same_day_nonstop flights and same_day_any flights be desired? The information is already being retrieved, so it wouldn't be very hard to filter.

> Continuing below is forward looking in case someone with very flexible plans might appreciate using the script to search around the date as well

This is also possible. However, I would want some confirmation that people would actually use this before implementing this feature as it is less trivial than the same_day_any/nonstop config options.

> If *any is selected, notification can send price deltas to original flight, lowest nonstop, and lowest connecting (if < -$1)

If I understand correctly, the notification would look something like this?
```
Found lower nonstop flight fare of <> for flight <> from <> to <> for <> <>
Found lower connecting flight fare of <> for flight <> from <> to <> for <> <>
```
If this is the case, I would just say notifying the user of the lowest fare (no matter nonstop or connecting) is sufficient and less confusing.

> Suggest adding the date as my use case repeats the same route many times

Just added this locally, so it will be available in the next version (either v7.X, v7.4.X, or 8v.0).

**Comment by StevenMassaro** [comment]
> This is also possible. However, I would want some confirmation that people would actually use this before implementing this feature as it is less trivial than the same_day_any/nonstop config options.

I would personally find value in this. I do this manually currently when I have a trip planned and the days don't really matter.

**Comment by babehboi** [comment]
I would concur with @StevenMassaro it's a useful function, I wonder if we would allow the user to set the delta?

**Comment by jdholtz** [comment]
> I wonder if we would allow the user to set the delta? I do wonder as we would need to set a limit to the -delta and +delta for the departure flight and return flight otherwise I would think it would error out if the look period is past the search date?

I'll definitely look at how feasible this is and how Southwest reacts to these deltas, but I can certainly set a limit on the maximum delta in the config.

**Comment by babehboi** [comment]
Question: which branch should I be on to test same day.  I have an opportunity for today and it dawned on me. TIA

**Comment by jdholtz** [comment]
I added support for the same day options (nonstop or all flights) in #303. If someone wants to see a range be searched instead of just the same day, could a new issue be created?
