### ISSUE TITLE
Running the script on MacOS prevents Chrome from opening if not already running

### ISSUE THREAD

**Issue by joewesch** [jdholtz/auto-southwest-check-in#219]
### Version

Auto-Southwest Check-In v7.1

### Browser Version

Chrome Version 121.0.6167.160 (Official Build) (arm64)

### Description

If the script is running I can't open Chrome by clicking on the icon in my dock. If Chrome is already open, it works fine but if I close it and try and re-open it then it won't open.

As a temporary workaround I can stop the script, open Chrome and then start the script again afterward.

### To Reproduce

1. Don't have Chrome open (Cmd+Q if open already)
2. Start the script
3. Try and open Chrome

### Expected Behavior

I expect Chrome to open a new window despite being used by the script in the background as a headless operation.

### Relevant logs and program output

```sh
N/A
```

### Additional context

Python 3.9.14
Apple M2 MacBook Pro
MacOS 13.4

**Comment by jdholtz** [comment]
What error do you get if you try to run Chrome from the command line while the script is running?

Can you reproduce the issue just using this small script below? If so, it is an upstream bug for SeleniumBase.
Run `python <file_name.py>` after saving it to a file to run the script.
```python
from seleniumbase import Driver

driver = Driver(uc=True, uc_cdp_events=True, headless=True)
driver.get("https://google.com")
driver.sleep(1000)
driver.quit()
```

**Comment by joewesch** [comment]
> What error do you get if you try to run Chrome from the command line while the script is running?

No error, just nothing happens.

```
~ ❯ open /Applications/Google\ Chrome.app
~ ❯ echo $?
0
~ ❯ 
```

> Can you reproduce the issue just using this small script below? If so, it is an upstream bug for SeleniumBase.

It doesn't open when I run that script either. In fact, I have to open Activity Monitor and search for and force quit Chrome just to get it to open again normally.

**Comment by joewesch** [comment]
Possibly related to: https://github.com/seleniumbase/SeleniumBase/issues/2375. Let me try updating to the version mentioned.

**Comment by jdholtz** [comment]
If you can reproduce the issue on the latest SeleniumBase version (4.23.2) with the script above, I would file an issue on its repository as changing anything in this repository won't likely fix the issue (it is reproducible without any code in this script).

**Comment by joewesch** [comment]
Confirmed still not working with the latest version.

I'll just use my workaround for now. I'm only using my Mac as a stop gap until the Docker image works again.

**Comment by jdholtz** [comment]
> I'll just use my workaround for now. I'm only using my Mac as a stop gap until the Docker image works again.

Sounds good. It may be helpful to still file a bug report just in case anyone else runs into the same issue.
