### ISSUE TITLE
Clarify editing notifications in docker

### ISSUE THREAD

**Issue by stgreenb** [jdholtz/auto-southwest-check-in#22]
I was taking the leap that if I made a config.json before I did the docker build it would pull it in, but maybe that's not the case?  Suggested method for adjusting the notifications for a docker run?

**Comment by jdholtz** [comment]
Hi! Do you mean that you changed the config.json after building the container? If so, for those changes to be applied to the container, you would need to rebuild it. You can also directly edit the config.json in the container, but those changes would only apply to that container, so it wouldn't be the best option.

 I can add a clarification for that in the README.

**Comment by stgreenb** [comment]
Yeah, that's it, just a note, ty.
