### ISSUE TITLE
Repeated check ins for a reservation that occurs in the past

### ISSUE THREAD

**Issue by grantland** [jdholtz/auto-southwest-check-in#24]
Feel free to close as `wontfix`, but in testing my image on a reservation that is currently open for checking in the script attempts to check in repeatedly without `docker kill`:

```
Checking in to flight from 'A' to 'B' for Grantland Chew

Successfully checked in to flight from 'A' to 'B' for Grantland Chew!
Grantland Chew got A51!

Checking in to flight from 'A' to 'B' for Grantland Chew

Successfully checked in to flight from 'A' to 'B' for Grantland Chew!
Grantland Chew got A51!

Checking in to flight from 'A' to 'B' for Grantland Chew

Successfully checked in to flight from 'A' to 'B' for Grantland Chew!
Grantland Chew got A51!
```

**Comment by jdholtz** [comment]
I can get this information. However, I think it would be helpful to still notify people if it has already been checked in. Maybe a `You have already checked in` message?

**Comment by grantland** [comment]
The main issue is that it continues to check in after successfully checking in the first time as I would expect the instance to exit with a successful response after the first successful check in.

**Comment by jdholtz** [comment]
Are these messages happening in the same instance of the script (i.e. it didn’t restart)? It should exit right after it has checked in. How much time passes in between attempts?

**Comment by grantland** [comment]
Same instance of the script and pretty much a few seconds in between

**Comment by jdholtz** [comment]
This might be an issue running it with Docker and the restart policy you are giving the container. Are you using `––restart-policy=always`? I think the container exits and restarts which explains why it keeps checking in (Docker doesn’t clear logs on a restart).

If you want Docker to start on boot, I think you can still use the `unless-stopped` restart policy without having this side effect. Let me know if this is the issue and I will update the README accordingly.

**Comment by grantland** [comment]
I used the following command:

```
docker run -d --restart unless-stopped auto-southwest-check-in CONFIRMATION FIRST LAST
```

**Comment by jdholtz** [comment]
Could you try it with the `on-failed` restart policy and see if it has the same issue?

**Comment by grantland** [comment]
You're right! I was using the wrong `--restart` flag and `--restart on-failure` solves the problem. Thanks!

**Comment by jdholtz** [comment]
Edited the title for clarity
