### ISSUE TITLE
Add account / reservation level notification settings

### ISSUE THREAD

**Issue by nicseltzer** [jdholtz/auto-southwest-check-in#246]
Add the ability to nest notification settings for accounts which then are inherited by reservations. Retain the ability to set global notification settings and instances.

**Comment by nicseltzer** [comment]
Sorry! I meant to file these on my fork as personal notes!

**Comment by jdholtz** [comment]
Account and reservation level notification settings already exist [here](https://github.com/jdholtz/auto-southwest-check-in/blob/master/CONFIGURATION.md#account-and-reservation-specific-configuration) here.
