### ISSUE TITLE
Can you attach multiple users to the process?

### ISSUE THREAD

**Issue by dylansison** [jdholtz/auto-southwest-check-in#26]
If you can't, I think it could be helpful if you're setting this up for your whole family and make reservations seperately, either by accident or intentionally.

Like having multiple USERNAME and PASSWORD arguments I think

**Comment by jdholtz** [comment]
This is a good idea. Would you prefer the arguments to be in `config.json` or passed through the command line? I could support both, but having many cli arguments might be confusing to some users.

**Comment by dylansison** [comment]
I’d say config.json or maybe a reference file you can link in the command line command?
in a perfect world you could have it be a docker container reference a file outside of the docker container so you can readily change which user’s accounts are being watched

**Comment by jdholtz** [comment]
You can link an outside file into Docker using [volumes](https://docs.docker.com/storage/volumes/). I haven’t tested it, but you should be able to add `--volume /path/to/config.json:/app/config.json` to the `docker run` command so you don’t have to rebuild the container every time you change the configuration. 

It would be unnecessarily complicated to have a file that is periodically read from the script as it is running (I’m not sure if this is what you are suggesting or not).  It doesn’t take long to rebuild/restart the Docker container in case of changes to the config file, so this wouldn't add any benefit.

**Comment by ericlamus** [comment]
+1 on this feature/suggestion.  I've been using two VMs for this.  Personally, I'd prefer command line argument as my girlfriend isn't always traveling with me.  But I guess we can use config-solo.json, versus config-family.json.

**Comment by jdholtz** [comment]
Would it be desired to have a separate configuration for each account/flight? I’ve started progress on this feature [here](https://github.com/jdholtz/auto-southwest-check-in/tree/multiple_accounts_and_flights). You can pass in additional accounts/flights into the config but every account would use the same notifications, interval, etc.

**Comment by dylansison** [comment]
I think, for simplicity, it'd work better to just have it scan all listed accounts for flights (daily?) since it's rare that you only want someone's flights to automatically be checked in sometimes (unless you're running this as a paid service).

If you mean configurables by account, I don't exactly see why you'd want people to be notified individually of their specific flight but it's possible I suppose?

About the file being read by the script from the Docker container, I suppose just to make sure no one forgets, if possible, add something that restarts the container when the file changes?

**Comment by jdholtz** [comment]
I will keep the configuration level at the global level for now, and can potentially make changes if per account configuration is desired.

To actually restart the script/container when the config file changes, I would need to add a separate service to rebuild/restart the Docker containers as changes don’t actually get made within the container (and continuous file-watching is a fairly complicated thing on its own). If someone else wants to create that service, that would be great but I want that to be separate from this project.
