### ISSUE TITLE
This should not be GET request as this url is only for POST

### ISSUE THREAD

**Issue by dmytrokoren** [jdholtz/auto-southwest-check-in#278]
### Version

develop

### Browser Version

latest

### Description

On the check-in the GET request fails.
https://github.com/jdholtz/auto-southwest-check-in/blob/67aa678d2ea51308aea0fd58f3dc5420af8f64f6/lib/checkin_handler.py#L189

### To Reproduce

mentioned in pull request

### Expected Behavior

I was looking into this issue why people where checked in properly but failed to retrieve the information.
while checking with postman, the request in 'description above" it only takes POST request, so GET is not required.

**Comment by jdholtz** [comment]
Should this request be a POST request or are you saying it is not necessary at all?

 I will look at the requests sent in a bit, but what’s been necessary up to this point is a GET request to fetch the passenger’s check-in token. Then the POST request is initiated. I haven’t checked in manually on the website in a while, but from what I remember you needed to click ‘Check-in’ (the GET request) and then ‘View boarding pass’ (the POST request).

**Comment by dmytrokoren** [comment]
@jdholtz I think SW changed their API... I'm not 100% certain but while messing around with APIs, I have noticed that we are doing GET request on "CHECKIN_URL = "mobile-air-operations/v1/mobile-air-operations/page/check-in/" - only accepts POST.

![CleanShot 2024-06-30 at 13 11 02@2x](https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/c583d198-a5f0-4e47-b675-6cea974252a6)

![CleanShot 2024-06-30 at 13 11 41@2x](https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/a624eef5-ec13-4388-89b6-1d47d90c6af3)




Another GET is "VIEW_RESERVATION_URL = "mobile-air-booking/v1/mobile-air-booking/page/view-reservation/" - only accepts POST.

![CleanShot 2024-06-30 at 13 12 22@2x](https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/c6881335-a9b5-4482-bc17-7bb531f7786d)

![CleanShot 2024-06-30 at 13 25 23@2x](https://github.com/jdholtz/auto-southwest-check-in/assets/26825098/7b73e9b2-b277-4acf-a120-5a2b4cf9b5c7)

**Comment by dmytrokoren** [comment]
> Should this request be a POST request or are you saying it is not necessary at all?
> 
> I will look at the requests sent in a bit, but what’s been necessary up to this point is a GET request to fetch the passenger’s check-in token. Then the POST request is initiated. I haven’t checked in manually on the website in a while, but from what I remember you needed to click ‘Check-in’ (the GET request) and then ‘View boarding pass’ (the POST request).

POST only, no more GET: (also "recordLocator" is now required with "firstName" and "lastName")
https://github.com/jdholtz/auto-southwest-check-in/blob/67aa678d2ea51308aea0fd58f3dc5420af8f64f6/lib/checkin_scheduler.py#L79-L80

POST only, no more GET: (also "recordLocator" is now required with "firstName" and "lastName")
https://github.com/jdholtz/auto-southwest-check-in/blob/67aa678d2ea51308aea0fd58f3dc5420af8f64f6/lib/checkin_handler.py#L186-L192

this should resolve this issue: https://github.com/jdholtz/auto-southwest-check-in/pull/274#issuecomment-2183474726

**Comment by jdholtz** [comment]
> I think SW changed their API

Yeah, I'm seeing that too. I will adapt it to the new API changes once I get a flight that has a check-in. Currently, my closest one is in a couple of months but if someone has a check-in sooner and wants to send me their reservation info privately I can make the changes sooner.

> I did same, clicked on Check-in and entered the info required on website and the request that was made was POST.

Gotcha. Is it only one click now? I meant to say that on the website you had to click 'Retrieve reservation' not 'Check in' but then you had to click another to actually view the boarding pass. Has this changed as well?

**Comment by dmytrokoren** [comment]
> > I think SW changed their API
> 
> Yeah, I'm seeing that too. I will adapt it to the new API changes once I get a flight that has a check-in. Currently, my closest one is in a couple of months but if someone has a check-in sooner and wants to send me their reservation info privately I can make the changes sooner.
> 
> > I did same, clicked on Check-in and entered the info required on website and the request that was made was POST.
> 
> Gotcha. Is it only one click now? I meant to say that on the website you had to click 'Retrieve reservation' not 'Check in' but then you had to click another to actually view the boarding pass. Has this changed as well?

I have one coming up in July, I can share, let me know where I can message you.

Another issue I'm facing, I'm monitoring 4 accounts, first account has two round trips and the fare check is working fine I can see +$xx but for the other 3 accounts I'm getting this message below:
```
2024-07-02 12:06:51 DEBUG Process-3[reservation_monitor:112]: Flight cannot be changed online. Skipping fare check 
```

**Comment by jdholtz** [comment]
> I have one coming up in July, I can share, let me know where I can message you.

Emailing it to me works (you can find it in the commit history or my website which is linked to this profile). 

For now, check-ins seem to be still be going through (probably for conforming to people who haven’t updated the SW app).

> Another issue I'm facing

This message means that the SW website doesn’t let you change a flight for a different price. I’ve seen a few scenarios this occurs but on my account now, one flight has a message saying “you can change your itinerary up to two times for free”. When pulling up the change page, no prices are listed (as it’s free to change) so the fare checker can’t do anything in this case and doesn’t attempt to check. 

What’s a bit strange is that the change link isn’t even populated in the response, so they must have more logic in their API to handle special cases like this which make it look like you can change the flight, but not actually for a lower price.

**Comment by aaron-pham** [comment]
> “you can change your itinerary up to two times for free”

Workaround for this is just to rebook the flight twice (use up your free ones) and the prices will come back.

**Comment by dmytrokoren** [comment]
@jdholtz I made new changes (Pull Request - pending): docker pull dmytrokoren/auto-southwest-check-in:develop

**Comment by dmytrokoren** [comment]
@jdholtz this folks SW keep on adding new parameters for POST request

Newly added param: passengerSearchToken

For now it's there without any value.

**Comment by aaron-pham** [comment]
Is this POST even needed @dmytrokoren ? I had a flight on 7/4 and 7/7 and my check-ins were successful.

**Comment by dmytrokoren** [comment]
> Is this POST even needed @dmytrokoren ? I had a flight on 7/4 and 7/7 and my check-ins were successful. 

@aaron-pham yes, this is to get needed information in order to do proper check-in. It was previously GET but checking with APi it's using POST

**Comment by aaron-pham** [comment]
@dmytrokoren how would my check-ins have been successful without the new changes though?

**Comment by dmytrokoren** [comment]
> @dmytrokoren how would my check-ins have been successful without the new changes though? 

If you change to GET it works too lol I don't know how but I switched to POST because that's how SW has it on their end.

Going to your question:

`def _check_in_to_flight(self) -> JSON:
        """
        First, make a GET request to get the needed check-in information. Then, make
        a POST request to submit the check in.
        """
        headers = self.checkin_scheduler.headers
        info = {
            "first-name": self.first_name,
            "last-name": self.last_name,
        }
        site = CHECKIN_URL + self.flight.confirmation_number

        logger.debug("Making GET request to check in")
        response = make_request("GET", site, headers, info)

        info = response["checkInViewReservationPage"]["_links"]["checkIn"]
        site = f"mobile-air-operations{info['href']}"

        logger.debug("Making POST request to check in")
        # Don't randomly sleep during this request to have it go through more quickly
        reservation = make_request("POST", site, headers, info["body"], random_sleep=False)
        return reservation `

**Comment by jdholtz** [comment]
> Is this POST even needed @dmytrokoren ?

The way it is currently, the first request provides a token that’s unique to you on the flight your checking in to. Then, the second request uses this token to perform the seat assignment. Even with SW’s changes, it appears the token is still needed so the first request is indeed required. 

> @dmytrokoren how would my check-ins have been successful without the new changes though?
My speculation is that the old method (currently in use for this script as of v7.5) is deprecated on their mobile API. However, SW needs to support old versions of the mobile app (for people that haven’t updated), so this old method for checking in should be working for a while as the script uses the mobile API.

**Comment by dmytrokoren** [comment]
#282
