### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by The-Kevster-101** [jdholtz/auto-southwest-check-in#285]
### Version

7.5

### Browser Version

Chrome

### Description

Traceback (most recent call last):
  File "southwest.py", line 59, in <module>
    init(arguments)
  File "southwest.py", line 52, in init
    from lib.main import main
  File "/Users/Kevin/auto-southwest-check-in/lib/main.py", line 11, in <module>
    from .config import GlobalConfig, ReservationConfig
  File "/Users/Kevin/auto-southwest-check-in/lib/config.py", line 177
    if check_fares := os.getenv("AUTO_SOUTHWEST_CHECK_IN_CHECK_FARES"):
                    ^
SyntaxError: invalid syntax

### To Reproduce

1. run
2. see error

### Additional context

Python 3.7.6 on Mac Terminal

**Comment by jdholtz** [comment]
> Python 3.7.6 on Mac Terminal

The script only supports Python 3.8 and above as that is what Selenium supports. The syntax issue you’re seeing here was added in Python 3.8.

**Comment by The-Kevster-101** [comment]
Thank you. I realized that after searching some.  I've updated to 3.12.4 and got it working.
