### ISSUE TITLE
TypeError when attempting to run script

### ISSUE THREAD

**Issue by ramenchef** [jdholtz/auto-southwest-check-in#3]
```
auto-southwest-check-in> python southwest.py ABC123 FIRST LAST
Checking in to flight from 'CITY_1' to 'CITY_2' for FIRST LAST
Scheduling checkin to flight from 'CITY_2' to 'CITY_1' for FIRST LAST at 2022-05-25 12:59:55 UTC

Failed to retrieve reservation. Reason: Bad Request 400
Exception in thread Thread-1:
Traceback (most recent call last):
  File "\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "\auto-southwest-check-in\lib\flight.py", line 78, in _set_check_in
    self._check_in()
  File "\auto-southwest-check-in\lib\flight.py", line 91, in _check_in
    info = response['checkInViewReservationPage']['_links']['checkIn']
TypeError: 'NoneType' object is not subscriptable

```
Not sure if this happens to all reservations or to just the return leg of a round trip reservation

**Comment by jdholtz** [comment]
Thanks for reporting this. That error is expected to be thrown when the script fails to retrieve a reservation (I have to fix that). 

The 400 error code indicates that there was a problem with the client. When you started the script, it attempted to check in to one of the flights right away. Was that flight already checked in or did it already depart before starting the script? There could be an issue with the script scheduling flights that it shouldn’t.

**Comment by ramenchef** [comment]
The confirmation number is for a round trip reservation. The first leg was already completed before running the script. I was attempting to run the script to check into the second half the confirmation (the return leg).

**Comment by jdholtz** [comment]
I’ll make sure to fix this the next time I have a round-trip flight scheduled. That might not be for a while though.

**Comment by ramenchef** [comment]
Just as another datapoint, I left the script running just to see if it would work. It did successfully check into the second/return leg of the round trip. So my guess right now is that the script is attempting to check into both legs of the trip, and the first leg fails because that flight already departed.

**Comment by jdholtz** [comment]
That's good to hear.

I found old data I had for a flight and was able to create a potential fix for this issue. Would you be able to test it with this branch? https://github.com/jdholtz/auto-southwest-check-in/tree/late-checkins-fix

It shouldn't even print out the message that it is checking in to the first flight if it works correctly.

**Comment by ramenchef** [comment]
Unfortunately, my 2nd flight is already completed. Using your branch, though, I do see that it silently exits after checking both flights of the confirmation.

**Comment by jdholtz** [comment]
Thanks for testing. If the script silently exited, that means that the change worked, so I will merge the branch and close this issue.
