### ISSUE TITLE
Checking in by account is able to login but  flight is under different name

### ISSUE THREAD

**Issue by dmytrokoren** [jdholtz/auto-southwest-check-in#31]
Checking in by account is able to login but flight reservation is under different name.

Account name: James Smith
Flight reservations: Jane Doe and John Doe

I'm not able to see flight checking scheduled after successful login message -- "Successfully logged in to James Smith's account"
Not seeing -- "Successfully scheduled the following flights to check in for Jane Doe & John Doe"

Please advise, thank you.
P.S - Great script simple to use.

**Comment by dmytrokoren** [comment]
Sorry, my mistake. Closing this issue as you can create user account on SW and use Rapid Reward number and it will bring that trip to your account.

**Comment by dmytrokoren** [comment]
Sorry, my mistake. Closing this issue as you can create user account on SW and use Rapid Reward number and it will bring that trip to your account.

**Comment by jdholtz** [comment]
Thanks for looking into that. If anyone has this same issue, I will redirect them to this comment.

**Comment by dmytrokoren** [comment]
@jdholtz If I logged in with my account and I have 2 passengers for my flight will it check in for them too or only for me?

**Comment by jdholtz** [comment]
Yes, that is the answer
