### ISSUE TITLE
Notification on Service Start

### ISSUE THREAD

**Issue by ctkubik** [jdholtz/auto-southwest-check-in#35]
I have my notifications enabled with Telegram; however, it would be really nice to have a notification when the service starts. For example, I have a vbs file which silently runs the service via cmd when my Windows machine restarts (I am not sure if this is required or not). It would be nice to have the service notify me that the system started properly.

Dumb question time:

Do I need to log-in/register the flight every time my system restarts?
It would be great to have the system provide a list of the flights registered and tracking
Do I need to have the vbs run the CMD each time my system starts or does the system run as a service automatically?
Not sure if this is helpful to others...but this is the vbs file code I use:

Set oShell = CreateObject ("Wscript.Shell")
Dim strArgs
strArgs = "cmd /c C:"southwest.py location on your PC" SWAUSERNAME SWAPASSWORD"
oShell.Run strArgs, 0, false

**Comment by ctkubik** [comment]
Thank you for entertaining my questions.  I am extremely excited about this project and I hope to contribute once I have a little more time...hence the dumb questions.  

If the computer/Docker restarts, any scripts/flights I had entered are cleared out.  Meaning, every time my system reboots I would need to re-enter the confirmation/name/user/pass.  Correct?

My vbs file enters my user/pass, but I wanted to make sure I completely understand how the system runs.  

The notification system is pretty sweet.  Thank you for your hard work!!!

**Comment by jdholtz** [comment]
> If the computer/Docker restarts, any scripts/flights I had entered are cleared out. Meaning, every time my system reboots I would need to re-enter the confirmation/name/user/pass. Correct?

Yes, but if you are using Docker, the arguments would already be supplied to the container before it is run and you wouldn't need to intervene manually after the restart.

I look forward to your contributions!

**Comment by ctkubik** [comment]
Perfect.  Thank you very much.  I created a few VBS files for each of my family members.  So, every time my computer reboots it will log each person into SWA and track their flights (I believe I can have more than one person being tracked based on what I read).

This is the VBS I created...which may be helpful to others.  Create a notepad file and rename it to "whatever you want".vbs.  I added these files to my Windows start folder.

In the notepad file, add the following.  There is a space before the user and pass...this is also a silent window, so you will not see the actual CMD window on your screen.  I have my notifications setup so I know it is running.  If you want to see the window...change the 0 to 1 and false to true.

Dim oShell, strPath, strUser, strPass
Set oShell = Wscript.CreateObject("WScript.Shell")
strPath = """C:\LOCATION OF YOUR FILES\southwest.py"""
strUser = " MYSWAUSER"
strPass = " MYSWAPASS"
oShell.Run strPath & strUser & strPass, 0, false

**Comment by jdholtz** [comment]
In #33, I added the ability to set up multiple accounts/flights in the same script using the configuration file. If you want to try that out instead, you will only need to run one instance of the script instead of multiple.

**Comment by ctkubik** [comment]
I will definitely check that out.  Thank you!

**Comment by schmeed** [comment]
> 

Anything else you need on Windows other than Python, southwest.py and your VBS files??

**Comment by ctkubik** [comment]
Not really...you'll need to run the pip install script as well.  I would suggest setting up the notification system...

The VBS file works really well (so far) in the startup folder.  

If you need help, let me know.  I just did this all over the past two days...so its fresh in my head, but I am not sure if it works (yet).  :)

**Comment by schmeed** [comment]
> Not really...you'll need to run the pip install script as well. I would suggest setting up the notification system...
> 
> The VBS file works really well (so far) in the startup folder.
> 
> If you need help, let me know. I just did this all over the past two days...so its fresh in my head, but I am not sure if it works (yet). :)

Would love your step by step instructions if you are willing.

**Comment by ctkubik** [comment]
For sure.  There could be a more streamlined way...I am not a total expert when it comes to CMD or Python...but I hope this helps you.  

- I installed Github and cloned the directory to my computer (you can just download the files and save them to your computer).
- Install Python (pretty self explanatory with an exe)
- Open CMD in Windows
- cd "the folder directory where you saved the files) (hit enter)
- pip install -r requirements.txt (hit enter)

This should install everything you need.

You should still be in your Southwest directory with the command prompt

-cd "the folder directory where you saved the files"\tests

Now you should be in the test folder of the directory

type pytest (hit enter)

The system should test the different files and tell you if it passed

If it did...great.

cd "the folder directory where you saved the files"

southwest.py CONFIRMATION_NUMBER FIRST_NAME LAST_NAME

Now...I did setup the notification system...which I would suggest doing.

in the same directory as above.  It may already be installed...but this doesn't hurt

pip install apprise

In Windows navigate to the Southwest directory with all your files.  Find the config.example.json file.  Right-click and open in Notepad.  In the notification_urls enter the information you find [HERE](https://github.com/caronc/apprise).

Then you can test if you did this correct by going to the CMD window

southwest.py --test-notifications (hit enter)

**Comment by schmeed** [comment]
Thank you @ctkubik!!  I will begin testing this shortly and report back.

**Comment by schmeed** [comment]
RESOLVED: Needed to install the visual c++ redistributable DLLs.

C:\swa\auto-southwest-check-in\tests>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0
rootdir: C:\swa\auto-southwest-check-in\tests
plugins: cov-4.0.0, mock-3.10.0, requests-mock-1.10.0
collected 67 items

test_checkin_handler.py .......                                                                                  [ 10%]
test_checkin_scheduler.py .............                                                                          [ 29%]
test_config.py .........                                                                                         [ 43%]
test_flight.py ...                                                                                               [ 47%]
test_flight_retriever.py ...                                                                                     [ 52%]
test_general.py ...                                                                                              [ 56%]
test_notification_handler.py .........                                                                           [ 70%]
test_southwest.py ........                                                                                       [ 82%]
test_webdriver.py ............                                                                                   [100%]

================================================= 67 passed in 4.77s ==================================================

**Comment by jdholtz** [comment]
You don’t need to run the unit tests before using the script. Those are mostly just for development. However, I’m not sure why there’s not a 100% pass rate as there is on the repository (as seen in the repository).

**Comment by schmeed** [comment]
> You don’t need to run the unit tests before using the script. Those are mostly just for development. However, I’m not sure why there’s not a 100% pass rate as there is on the repository (as seen in the repository).

I did get a 100% pass...cumulatively.  67 passed.  Do you think each one should show 100%?  I'm not familiar with pytest, so I'm in the dark.

**Comment by jdholtz** [comment]
There should be a 100% pass rate on the tests. Without seeing the errors they are failing with, I’m not able to see what exactly is wrong. However, it shouldn’t affect the script running on your computer or in Docker.

**Comment by schmeed** [comment]
Well, again, I'm not a pytest expert and I did not stay at a Holiday Inn Express last night...but I ran the test again with verbosity and it shows all tests passed.  I believe it reports the % passed as a cumulative running total.  From 0% to 100% as it works through all tests.  🤷‍♂️

============================= test session starts =============================
platform win32 -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0 -- C:\Users\Dave\AppData\Local\Programs\Python\Python311\python.exe
cachedir: .pytest_cache
rootdir: C:\swa\auto-southwest-check-in\tests
plugins: cov-4.0.0, mock-3.10.0, requests-mock-1.10.0
collecting ... collected 67 items

test_checkin_handler.py::test_schedule_check_in_starts_a_process PASSED  [  1%]
test_checkin_handler.py::test_set_check_in_correctly_sets_up_check_in_process PASSED [  2%]
test_checkin_handler.py::test_wait_for_check_in_exits_immediately_if_checkin_time_has_passed PASSED [  4%]
test_checkin_handler.py::test_wait_for_check_in_sleeps_once_when_check_in_is_less_than_ten_minutes_away PASSED [  5%]
test_checkin_handler.py::test_wait_for_check_in_refreshes_headers_ten_minutes_before_check_in PASSED [  7%]
test_checkin_handler.py::test_check_in_sends_error_notification_when_check_in_fails PASSED [  8%]
test_checkin_handler.py::test_check_in_sends_success_notification_on_successful_check_in PASSED [ 10%]
test_checkin_scheduler.py::test_schedule_schedules_all_reservations PASSED [ 11%]
test_checkin_scheduler.py::test_schedule_flights_schedules_all_flights_under_reservation PASSED [ 13%]
test_checkin_scheduler.py::test_schedule_flights_does_not_schedule_already_scheduled_flights PASSED [ 14%]
test_checkin_scheduler.py::test_schedule_flights_does_not_schedule_departed_flights PASSED [ 16%]
test_checkin_scheduler.py::test_get_reservation_info_returns_reservation_info PASSED [ 17%]
test_checkin_scheduler.py::test_get_reservation_info_sends_error_notification_when_reservation_retrieval_fails PASSED [ 19%]
test_checkin_scheduler.py::test_flight_is_scheduled_returns_true_if_flight_is_already_scheduled PASSED [ 20%]
test_checkin_scheduler.py::test_flight_is_scheduled_returns_false_if_flight_is_not_scheduled[flight_info0-flight_time0] PASSED [ 22%]
test_checkin_scheduler.py::test_flight_is_scheduled_returns_false_if_flight_is_not_scheduled[flight_info1-flight_time1] PASSED [ 23%]
test_checkin_scheduler.py::test_flight_is_scheduled_returns_false_if_flight_is_not_scheduled[flight_info2-flight_time2] PASSED [ 25%]
test_checkin_scheduler.py::test_set_headers_sets_new_headers PASSED      [ 26%]
test_checkin_scheduler.py::test_remove_departed_flights_removes_only_departed_flights[flight_time0-1] PASSED [ 28%]
test_checkin_scheduler.py::test_remove_departed_flights_removes_only_departed_flights[flight_time1-0] PASSED [ 29%]
test_config.py::test_config_exits_on_error_in_config_file PASSED         [ 31%]
test_config.py::test_get_config_reads_the_config_file_correctly PASSED   [ 32%]
test_config.py::test_get_config_returns_empty_config_when_file_is_not_found PASSED [ 34%]
test_config.py::test_parse_config_raises_exception_with_invalid_entries[config_content0] PASSED [ 35%]
test_config.py::test_parse_config_raises_exception_with_invalid_entries[config_content1] PASSED [ 37%]
test_config.py::test_parse_config_raises_exception_with_invalid_entries[config_content2] PASSED [ 38%]
test_config.py::test_parse_config_sets_the_correct_config_values PASSED  [ 40%]
test_config.py::test_parse_config_does_not_set_values_when_a_config_value_is_empty PASSED [ 41%]
test_config.py::test_parse_config_sets_retrieval_interval_to_a_minimum PASSED [ 43%]
test_flight.py::test_get_flight_time_returns_the_correct_time PASSED     [ 44%]
test_flight.py::test_get_airport_timezone_returns_the_correct_timezone PASSED [ 46%]
test_flight.py::test_convert_to_utc_converts_local_time_to_utc PASSED    [ 47%]
test_flight_retriever.py::test_flight_retriever_schedules_reservations_correctly PASSED [ 49%]
test_flight_retriever.py::test_account_FR_monitors_the_account_continuously PASSED [ 50%]
test_flight_retriever.py::test_get_flights_returns_the_correct_flights PASSED [ 52%]
test_general.py::test_make_request_raises_exception_on_failure PASSED    [ 53%]
test_general.py::test_make_request_correctly_posts_data PASSED           [ 55%]
test_general.py::test_make_request_correctly_gets_data PASSED            [ 56%]
test_notification_handler.py::test_get_account_name_returns_the_correct_name PASSED [ 58%]
test_notification_handler.py::test_send_nofication_does_not_send_notifications_if_level_is_too_low PASSED [ 59%]
test_notification_handler.py::test_send_notification_sends_notifications_with_the_correct_content[2] PASSED [ 61%]
test_notification_handler.py::test_send_notification_sends_notifications_with_the_correct_content[None] PASSED [ 62%]
test_notification_handler.py::test_new_flights_sends_no_notification_if_no_flights_exist PASSED [ 64%]
test_notification_handler.py::test_new_flights_sends_notifications_for_new_flights PASSED [ 65%]
test_notification_handler.py::test_failed_retrieval_reservation_sends_error_notification PASSED [ 67%]
test_notification_handler.py::test_successful_checkin_sends_notification_for_check_in PASSED [ 68%]
test_notification_handler.py::test_failed_checkin_sends_error_notification PASSED [ 70%]
test_southwest.py::test_set_up_prints_version_when_flag_is_passed[-v] PASSED [ 71%]
test_southwest.py::test_set_up_prints_version_when_flag_is_passed[--version] PASSED [ 73%]
test_southwest.py::test_set_up_sends_test_notifications_when_flag_is_passed PASSED [ 74%]
test_southwest.py::test_set_up_monitors_account_when_a_username_and_password_are_provided PASSED [ 76%]
test_southwest.py::test_set_up_schedules_checkin_when_a_confirmation_number_and_name_are_provided PASSED [ 77%]
test_southwest.py::test_set_up_sends_error_message_when_arguments_are_invalid[arguments0] PASSED [ 79%]
test_southwest.py::test_set_up_sends_error_message_when_arguments_are_invalid[arguments1] PASSED [ 80%]
test_southwest.py::test_set_up_sends_error_message_when_arguments_are_invalid[arguments2] PASSED [ 82%]
test_webdriver.py::test_get_driver_returns_a_webdriver_with_one_request PASSED [ 83%]
test_webdriver.py::test_set_headers_from_request_sets_the_correct_headers PASSED [ 85%]
test_webdriver.py::test_get_checkin_info_returns_request_headers PASSED  [ 86%]
test_webdriver.py::test_get_flights_sets_account_name_when_it_is_not_set PASSED [ 88%]
test_webdriver.py::test_get_account_info_does_not_set_account_name_when_it_is_already_set PASSED [ 89%]
test_webdriver.py::test_get_options_adds_the_necessary_options PASSED    [ 91%]
test_webdriver.py::test_get_needed_headers_returns_matching_headers[original_headers0-expected_headers0] PASSED [ 92%]
test_webdriver.py::test_get_needed_headers_returns_matching_headers[original_headers1-expected_headers1] PASSED [ 94%]
test_webdriver.py::test_get_needed_headers_returns_matching_headers[original_headers2-expected_headers2] PASSED [ 95%]
test_webdriver.py::test_get_needed_headers_returns_matching_headers[original_headers3-expected_headers3] PASSED [ 97%]
test_webdriver.py::test_get_needed_headers_returns_matching_headers[original_headers4-expected_headers4] PASSED [ 98%]
test_webdriver.py::test_set_account_name_sets_the_correct_values_for_the_name PASSED [100%]

============================= 67 passed in 1.37s ==============================

**Comment by ctkubik** [comment]
Nice!  Sorry I wasn't able to assist the past few days.  I have a flight for my wife next week, so that will be the first opportunity to give my sysem a shot.  Hopefully it works as intended.  Good luck!

**Comment by schmeed** [comment]
> Nice! Sorry I wasn't able to assist the past few days. I have a flight for my wife next week, so that will be the first opportunity to give my sysem a shot. Hopefully it works as intended. Good luck!

Please let us know!

**Comment by ctkubik** [comment]
I setup the system to log my buddy in for a flight today (15 minutes ago) and I am not sure if it worked or not.  Should I get a notification of a successful check-in (the registration was successful)?  I did go to the website and I ultimately checked him in, but I am not sure if the system worked or if my manual checkin worked.

**Comment by ctkubik** [comment]
It would be really cool if the system e-mailed the boarding passes after checking the person in for the flight.

**Comment by schmeed** [comment]
> I setup the system to log my buddy in for a flight today (15 minutes ago) and I am not sure if it worked or not. Should I get a notification of a successful check-in (the registration was successful)? I did go to the website and I ultimately checked him in, but I am not sure if the system worked or if my manual checkin worked.

If you have notifications setup properly, it will send you an email with boarding position.

`def successful_checkin(self, boarding_pass: Dict[str, Any], flight: Flight) -> None:
        success_message = (
            f"Successfully checked in to flight from '{flight.departure_airport}' to "
            f"'{flight.destination_airport}' for {self._get_account_name()}!\n"
        )

        for flight_info in boarding_pass["flights"]:
            for passenger in flight_info["passengers"]:
                success_message += f"{passenger['name']} got {passenger['boardingGroup']}{passenger['boardingPosition']}!\n"`

**Comment by ctkubik** [comment]
I'm thinking I need to update to the develop branch.  Is the best way to do that by downloading the files and simply copying them over?  Or is there a cmd command I can run to switch the branch?

**Comment by ctkubik** [comment]
I believe I updated the files to the develop branch.  I am thinking maybe the v1 from the master didn't allow more than one person (I had 4).  I believe this should fix that issue.  My wife's flight check-in will be tomorrow so I hope it works.

**Comment by ctkubik** [comment]
Dope.  I checked my buddy in again and it sent me the boarding position.  Fingers crossed it works tomorrow.  Cheers!

**Comment by jdholtz** [comment]
> I setup the system to log my buddy in for a flight today (15 minutes ago) and I am not sure if it worked or not. Should I get a notification of a successful check-in (the registration was successful)?

Did you get a notification that it scheduled the flight successfully? If you did, it should also send you a successful check-in notification. It might not have worked if this is the case. You can also check the output of the script. Since you are running it in the background, I advise you to still pipe the output of the script to a file so you can check the output if you need to. 

> It would be really cool if the system e-mailed the boarding passes after checking the person in for the flight.

I can look into this. However, I don't know how feasible this is because the script doesn't actually know where it is sending notifications to -- that is handled by [Apprise](https://github.com/caronc/apprise). Therefore, it won't be able to send it the boarding pass only on emails (unless this is possible with the Apprise API). Would you want it to attach the link to the boarding pass in the e-mail? You won't be able to actually view it without authentication, so I don't see much of a point in doing this (I could just add the website link to the notification). Let me know your thoughts on this.

> I'm thinking I need to update to the develop branch. Is the best way to do that by downloading the files and simply copying them over? Or is there a cmd command I can run to switch the branch?

You can use `git checkout develop` to move to that branch. I will add a note about this in the README.
