### ISSUE TITLE
Sleep Length too Large

### ISSUE THREAD

**Issue by ctkubik** [jdholtz/auto-southwest-check-in#44]
### Description

Successfully scheduled the following flights to check in for FIRST LAST:
Flight from ORIGIN to DESTINATION at 2023-04-02 19:45:00 UTC
Flight from ORIGIN to DESTINATION at 2023-04-29 12:45:00 UTC

Process Process-1:2:
Traceback (most recent call last):
File "C:\Users\ctkub\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
self.run()
File "C:\Users\ctkub\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\ctkub\Desktop\Southwest Checkin\lib\checkin_handler.py", line 40, in _set_check_in
self._wait_for_check_in(checkin_time)
File "C:\Users\ctkub\Desktop\Southwest Checkin\lib\checkin_handler.py", line 53, in _wait_for_check_in
time.sleep(sleep_time)
OverflowError: sleep length is too large

### To Reproduce

Log into an account with a future flight a few months out

**Comment by jdholtz** [comment]
Hey @ctkubik. I have a possible fix in the [fix-sleep](https://github.com/jdholtz/auto-southwest-check-in/tree/fix-sleep) branch. Can you test it out to see if this issue is fixed? Thanks!

**Comment by ctkubik** [comment]
I'd be happy to test it out.  I'll be available pretty much all weekend.

**Comment by ctkubik** [comment]
@jdholtz I was able to schedule the flight check-in for my moms flight in April.  I probably should have tried this prior to updating the file, but it did work.

**Comment by jdholtz** [comment]
Great! If you did want to try the previous code, you could either use git to checkout to the `develop` branch or just get the old file from that branch instead of the `fix-sleep` branch

**Comment by ctkubik** [comment]
@jdholtz I stopped being lazy and restored the master branch checkin_handler.py file and the error is back.  It looks like the updated file fixed the issue.

**Comment by jdholtz** [comment]
Thanks for checking! I will create a PR and merge the fix into the `develop` branch.
