### ISSUE TITLE
Add docker image to public repo

### ISSUE THREAD

**Issue by drippyer** [jdholtz/auto-southwest-check-in#49]
### Description

I think it would be easier for users to incorporate this tool into their existing workflow/system if it were available as a prebuilt image on a public repository (like Docker Hub or GitHub Container Registry).

It would appear that the process for publishing to a public repo is not overly convoluted ([DockerHub](https://docs.docker.com/docker-hub/repos/) / [GH CR](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)), but does seem to be something better done by an active dev on the project as opposed to someone like me hahaha. Still, if there is anything I can do to help, I am happy to do so.

This would allow for seamless integration with existing docker-compose containers as well as streamline the process of starting, restarting, and updating the container.

### What alternatives have you considered?

The existing method of pulling the git repo, inspecting then rebuilding the image if there have been modifications, and then starting the container, all necessitating the use of the documentation and scanning prior commands to ensure proper syntax.

**Comment by victorbutler** [comment]
Coincidentally, I happened to be looking at this exact thing just now. I haven't done it before, but [dgtlmoon](https://github.com/dgtlmoon) / [changedetection.io](https://github.com/dgtlmoon/changedetection.io) seems to do this nicely via GitHub Container Registry when a new release is tagged.

https://github.com/dgtlmoon/changedetection.io/blob/master/.github/workflows/containers.yml for reference

**Comment by jdholtz** [comment]
This is a good idea. However, the original image would not have the user's `config.json`. I could set up a volume in the image and link it to a location in the filesystem, but that is OS-dependent and might limit where the config file can reside. Thoughts on this? I'm not sure if Docker already has an inbuilt system for this (possibly by specifying the `--volume` flag in the `docker run` command).

**Comment by drippyer** [comment]
> I could set up a volume in the image and link it to a location in the filesystem, but that is OS-dependent and might limit where the config file can reside. Thoughts on this? I'm not sure if Docker already has an inbuilt system for this (possibly by specifying the `--volume` flag in the `docker run` command).

Docker standalone run has the `--mount` and `--volume` [flags](https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag) for mounting to a local directory, and docker-compose uses 
```
  container:
    image: repo/image
    volumes:
      - local_relative_dir:/container_dir
```

It should be feasible for users to create a local directory (something like `auto-southwest-data`) to house the `config.json`, and automatically create an `config.example.json` in the user-defined directory if it doesn't exist, checking beforehand to make sure that a valid `config.json` is not already present. Then the container should run normally if there is a valid `config.json`, or exit with information to the user explaining how to modify it. 

I can try to look into some of the other containers I have in use to see if I can understand their volume/config/data management when user data is required, though [Apprise](https://github.com/caronc/apprise) is one that immediately comes to mind.

**Comment by jdholtz** [comment]
Thanks for the detailed response @drippyer. I will look into how other projects currently do it and how I could replicate that for this project.

**Comment by jdholtz** [comment]
Hey @drippyer. In #55, I added a workflow to automatically build the image when a release is published. Additionally, I updated the documentation to point users to download the image from my public repository. Could you pull the image to make sure everything is working how you want it? The only image currently available is `jdholtz/auto-southwest-check-in:develop`. The repository can be found [here](https://hub.docker.com/repository/docker/jdholtz/auto-southwest-check-in).

**Comment by jdholtz** [comment]
Currently, only `develop` image tags are created. The `latest` and `vX.X` images will be created after the next release.
