### ISSUE TITLE
Error in Readme for getting --help

### ISSUE THREAD

**Issue by netpappy** [jdholtz/auto-southwest-check-in#61]
### Description

The following line should be python3 versus python for getting the help information.

python southwest.py --help 

Should be 

python3 southwest.py --help

<img width="296" alt="Screenshot 2023-03-19 at 5 21 01 PM" src="https://user-images.githubusercontent.com/56052521/226210958-b92c6873-7eaf-4c11-a79e-0a4a1128f0e3.png">

### To Reproduce

Run from a command prompt

python southwest.py --help

Error:  

Traceback (most recent call last):
  File "southwest.py", line 6, in <module>
    from lib.main import main
  File "/home/joe/apps/auto-southwest-check-in/lib/main.py", line 36
    def print_version() -> None:
                        ^
SyntaxError: invalid syntax

### Expected Behavior

Auto-Southwest Check-In v3.0

Schedule a check-in:
    python3 southwest.py CONFIRMATION_NUMBER FIRST_NAME LAST_NAME

Log into your account:
    python3 southwest.py USERNAME PASSWORD

Options:
    --test-notifications Test the notification URLs configuration and exit
    -v, --verbose        Emit debug messages to stderr
    -h, --help           Display this help and exit
    -V, --version        Display version information and exit

For more information, check out https://github.com/jdholtz/auto-southwest-check-in#readme

### Version

Auto-Southwest Check-In v3.0

### Additional context

I will submit a pull request with the fix...

**Comment by netpappy** [comment]
I submitted the following pull request for this issue... 

https://github.com/jdholtz/auto-southwest-check-in/pull/62

**Comment by jdholtz** [comment]
Merged #62. Thanks for the fix!
