### ISSUE TITLE
Script doesn't return to command prompt

### ISSUE THREAD

**Issue by schmeed** [jdholtz/auto-southwest-check-in#8]
Ran the script and it hasn't returned to the command prompt.  Is this the expected behavior? It just sits waiting to check in at the specified time?

What if my desktop reboots?

<img width="559" alt="image" src="https://user-images.githubusercontent.com/26189534/187555480-806ded27-9083-4170-816c-3d3aae38535d.png">

**Comment by ericlamus** [comment]
(Just stumbled onto this.)  I think this might be expected behavior.  You can stick it in a VM or Docker container.  I just spun up a VM and stuck it in there.

**Comment by jdholtz** [comment]
Yes, this is expected behavior. I have been wanting to put provide a Docker image with the script but just haven't had the time to test it with flights yet. My next task will be to create a Docker image for this, but PRs are welcome if you (or anyone) wants to implement this feature. 

#5 attempted to implement this, but was closed as the maintainer did not want to work on it anymore

**Comment by schmeed** [comment]
> Yes, this is expected behavior. I have been wanting to put provide a Docker image with the script but just haven't had the time to test it with flights yet. My next task will be to create a Docker image for this, but PRs are welcome if you (or anyone) wants to implement this feature.
> 
> #5 attempted to implement this, but was closed as the maintainer did not want to work on it anymore

Ok, thanks.  So, if my desktop reboots before either the outbound or return flight, just run the southwest.py script again before check in?

**Comment by jdholtz** [comment]
Yes. Another option is to run it on a server that is up all of the time. However, you would obviously need access to this which could be a problem for most users.

**Comment by schmeed** [comment]
> 

Awesome, thanks!  Last question (I think).  If I have multiple flights to check in (not in the same account) can I run multiple instances of the script in separate terminals?

**Comment by jdholtz** [comment]
Yes. I am also planning to add a feature to allow multiple accounts within one script, but for right now multiple instances of the script will work.
