### ISSUE TITLE
Check Fare Bug

### ISSUE THREAD

**Issue by pltrant** [jdholtz/auto-southwest-check-in#86]
### Description

I have my configuration setup with my account credentials and to check for updated fares every 24 hours.  Just started it and after logging into my account, it then returns this error:

```
Unexpected error during fare check: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "C:\Southwest_Check_in\auto-southwest-check-in\lib\flight_retriever.py", line 78, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "C:\Southwest_Check_in\auto-southwest-check-in\lib\fare_checker.py", line 31, in check_flight_price
    flight_price = self._get_flight_price(flight)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Southwest_Check_in\auto-southwest-check-in\lib\fare_checker.py", line 50, in _get_flight_price
    return self._get_matching_fare(new_flight["fares"], fare_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Southwest_Check_in\auto-southwest-check-in\lib\fare_checker.py", line 144, in _get_matching_fare
    for fare in fares:
TypeError: 'NoneType' object is not iterable
```

### To Reproduce

1. Setup the config.json with login account information and set to check fare.
2. Run `python southwest.py`
3. After the script logs in, it tries to check the fare and results in the above error.

### Version

`Auto-Southwest Check-In v4.0`

**Comment by jdholtz** [comment]
Thanks for reporting this quickly. What fare is this flight under? Also, does Southwest's website show the correct prices/points when you check for fares on their website?

**Comment by pltrant** [comment]
Hi. The fare is under Wanna Get Away. It's multiple tickets under my account (for family members - all under the same reservation number).

I can manually check my reservation and check for a change of flight to see any price differences for changing the flight.

**Comment by jdholtz** [comment]
Does this bug happen for every single one of the reservations?

Unfortunately, this is hard to debug on my end because I am not seeing the issue and a lot of the information that the script grabs for fare checking is private. If you do have some experience with Python and/or web scraping, it would be very helpful for you to look further into this if you have time.

**Comment by pltrant** [comment]
Here's the entire output:

```C:\auto-southwest-check-in> python southwest.py
Successfully logged in to Soandso's account

Successfully scheduled the following flights to check in for Soandso (edited out names and actual locations):
Flight from Denver to Phoenix at 2023-06-14 11:00:00 UTC
Flight from Phoenix to Denver at 2023-06-24 20:35:00 UTC

Unexpected error during fare check: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "C:\auto-southwest-check-in\lib\flight_retriever.py", line 78, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "C:\auto-southwest-check-in\lib\fare_checker.py", line 31, in check_flight_price
    flight_price = self._get_flight_price(flight)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\auto-southwest-check-in\lib\fare_checker.py", line 50, in _get_flight_price
    return self._get_matching_fare(new_flight["fares"], fare_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\auto-southwest-check-in\lib\fare_checker.py", line 144, in _get_matching_fare
    for fare in fares:
TypeError: 'NoneType' object is not iterable```

**Comment by jdholtz** [comment]
Thanks for the logs. That’s good to know that it is still working for the return flight. 

Just to verify, there is a price difference on the website for the outbound flight (the first one), not only the returning flight?

To debug this a little further, can you add `print(new_flight["startingFromPriceDifference"])` on line 50 of `lib/fare_checker.py` and paste the output you get (it might be None or something like {amount: …})?

**Comment by pltrant** [comment]
For the outbound flight, there's no tickets available under the Wanna Get Away fare type (but there is for the higher fare types).  For the return flight, there are still tickets available under the Wanna Get Away fare type (that cost $1 more).

Adding `print(new_flight["startingFromPriceDifference"])` resulted in this error: `Unexpected error during fare check: KeyError('startingFromPriceDifference')`.  I then changed it print all of `new_flight`, which results in (edited some of the values for privacy):

```
{'departureTime': '08: 00', 'arrivalTime': '12: 40', 'duration': '6h 40m', 'stopDescription': '1 Stop, STL', 'stopDescriptionOnSelect': '1 Stop, Change planes STL', 'shortStopDescription': '1 Stop', 'stopCity': 'STL', 'flightNumbers': '1234/5678', 'fareDifferences': ['unavailable', 'unavailable', 'unavailable', 'unavailable', 'unavailable', 'unavailable'
    ], 'startingFromPrice': None, 'startingFromPricePointTax': None, 'dynamicWaiverAvailabilityText': None, 'reasonIfUnavailable': 'Unavailable', 'discountedStartingFromPrice': None, 'discountedStartingFromPriceTax': None, 'fares': None, '_meta': {'cardId': 'DEN:PHX: 0: 2023-06-14', 'durationMinutes': 520, 'numberOfStops': 1, 'startingFromAmount': 0, 'departureTime': '0800'
    }, 'isNextDayArrival': False, 'hasLowestFare': False
}
```

**Comment by pltrant** [comment]
Sure.  Looking forward the new feature!  Once you have it available on a new branch, let me know and I can test it.

**Comment by jdholtz** [comment]
Hey @pltrant, I added a potential fix on the `handle_no_fares` branch. Could you switch to that branch and let me know if it fixes the issue for you. 

I decided to report back a price difference of 0 USD/Points because the fare is no longer available (sold out).

**Comment by pltrant** [comment]
Hi @jdholtz.  That does appear to have resolved the issue.  Thanks!

**Comment by jdholtz** [comment]
Thanks for testing!
