### ISSUE TITLE
Notifications don't seem to be working correctly

### ISSUE THREAD

**Issue by ericlamus** [jdholtz/auto-southwest-check-in#9]
I just used this for the first time.  It's awesome!  I spun up a Fedora VM with GUI, installed Chrome, and it worked perfectly.  Thank you so much!

```
[eric@localhost-live auto-southwest-check-in]$ cat config.json
{
	"notification_urls": "pover://REDACTED@REDACTED",
	"notification_level": 1
}
[eric@localhost-live auto-southwest-check-in]$ python3 southwest.py --test-notifications
Sending test notifications...
[eric@localhost-live auto-southwest-check-in]$ apprise -vv -t "Test Message Title" -b "Test Message Body" pover://REDACTED@ REDACTED
2022-08-31 23:09:33,527 - INFO - Notifying 1 service(s) asynchronously.
2022-08-31 23:09:33,866 - INFO - Sent Pushover notification to ALL_DEVICES.
[eric@localhost-live auto-southwest-check-in]$ 

```

I successfully received the test notification on my iPhone's Pushover app.  However, when actually running southwest.py...

```
Successfully logged in to Eric REDACTED's account

Scheduling checkin to flight from 'REDACTED' to 'REDACTED' for Eric REDACTED at 2022-09-01 REDACTED UTC

Scheduling checkin to flight from 'REDACTED' to 'REDACTED' for Eric REDACTED at 2022-09-04 REDACTED UTC

Checking in to flight from 'REDACTED' to 'REDACTED' for Eric REDACTED

Successfully checked in to flight from 'REDACTED' to 'REDACTED for Eric REDACTED!
Eric REDACTED got B01!
Joe REDACTED got B02!
```

... it didn't send the send the notification.  Does it only send the notification once both legs (roundtrip) are checked in?

Just in case Southwest "TOS team" stumbles on this, I redacted the above output so I won't get in trouble. ;)

**Comment by jdholtz** [comment]
Hi. Glad you like it! I had a flight a few days ago and ran into the same issue. I got the scheduling notification correctly but didn’t get the successful check-in notification as well. It’s strange because it worked [here](https://github.com/jdholtz/auto-southwest-check-in/issues/4#issuecomment-1221190044). 

It seems to be an issue with Apprise, so I will look into fixing that within the next few days. Thanks for reporting this!

**Comment by jdholtz** [comment]
Hey @ericlamus. I was able to reproduce the issue without actually needing a flight and have fixed it. Would you be willing to try it out for your next flight? You can find the changes [here](https://github.com/jdholtz/auto-southwest-check-in/tree/fix-notifications). Just run `git pull` and `git checkout fix-notifications` to use the new fix.

**Comment by ericlamus** [comment]
Done!  My next flight is Monday (check-in Sunday).  Will keep you posted!  Thanks again!

**Comment by ericlamus** [comment]
Hi @jdholtz , I can confirm that the notification worked two times with pover/Pushover on 9/4.  Thanks!

**Comment by jdholtz** [comment]
Great! Thanks for confirming!
